import { z } from "zod";
import { protectedProcedure, router } from "../_core/trpc";
import * as db from "../db";
import { assessCenterCapacity, assessOperationalLoad, buildTrialTimeline, calculateSampleSize, designOptions, designSteps, evaluateDesignCoherence, evaluateTrialAudit, forecastRecruitment, generateTheoreticalRandomisation, scoreProtocolComplexity } from "../studyDesign";

const projectInput = z.object({ studyId: z.string().min(3).max(80).regex(/^[A-Z0-9-]+$/), acronym: z.string().max(80).optional(), title: z.string().min(5).max(500), shortTitle: z.string().max(240).optional(), studyQuestion: z.string().max(4000).optional(), indication: z.string().max(300).optional(), condition: z.string().max(300).optional(), sponsor: z.string().max(300).optional(), coordinatingCenter: z.string().max(300).optional(), principalInvestigator: z.string().max(300).optional(), studyType: z.string().max(120).optional(), interventionType: z.string().max(160).optional(), phase: z.string().max(120).optional(), jurisdiction: z.string().max(160).default("International / à préciser"), status: z.enum(["DRAFT", "IN_REVIEW", "READY_FOR_REVIEW", "ARCHIVED"]).default("DRAFT"), protocolVersion: z.string().max(80).default("v0.1") });

export const studyDesignRouter = router({
  steps: protectedProcedure.query(() => designSteps),
  list: protectedProcedure.query(({ ctx }) => db.listStudyProjects(ctx.user.id)),
  detail: protectedProcedure.input(z.object({ id: z.number().int().positive() })).query(async ({ ctx, input }) => { const project = await db.getStudyProject(ctx.user.id, input.id); if (!project) throw new Error("Projet introuvable ou non autorisé."); return project; }),
  create: protectedProcedure.input(projectInput).mutation(({ ctx, input }) => db.createStudyProject(ctx.user.id, input)),
  update: protectedProcedure.input(projectInput.extend({ id: z.number().int().positive(), changeReason: z.string().min(3).max(600) })).mutation(async ({ ctx, input }) => { const { id, changeReason, ...data } = input; const updated = await db.updateStudyProject(ctx.user.id, id, data, changeReason); if (!updated) throw new Error("Projet introuvable ou non autorisé."); return { updated: true }; }),
  section: router({
    save: protectedProcedure.input(z.object({ studyProjectId: z.number().int().positive(), sectionKey: z.string().min(2).max(80), title: z.string().min(2).max(240), payload: z.record(z.string(), z.unknown()), completionState: z.enum(["NOT_STARTED", "IN_PROGRESS", "COMPLETE", "NEEDS_REVIEW"]) })).mutation(async ({ ctx, input }) => { const saved = await db.saveStudySection(ctx.user.id, input); if (!saved) throw new Error("Projet introuvable ou non autorisé."); return saved; }),
    coherence: protectedProcedure.input(z.object({ studyProjectId: z.number().int().positive() })).query(async ({ ctx, input }) => { const project = await db.getStudyProject(ctx.user.id, input.studyProjectId); if (!project) throw new Error("Projet introuvable ou non autorisé."); return evaluateDesignCoherence(project.sections); }),
  }),
  audit: router({
    run: protectedProcedure.input(z.object({ studyProjectId: z.number().int().positive() })).query(async ({ ctx, input }) => { const project = await db.getStudyProject(ctx.user.id, input.studyProjectId); if (!project) throw new Error("Projet introuvable ou non autorisé."); return evaluateTrialAudit(project.sections); }),
  }),
  collaboration: router({
    addMember: protectedProcedure.input(z.object({ studyProjectId: z.number().int().positive(), userId: z.number().int().positive(), projectRole: z.enum(["EDITOR", "REVIEWER", "VIEWER"]) })).mutation(async ({ ctx, input }) => { const saved = await db.addStudyProjectMember(ctx.user.id, input.studyProjectId, input.userId, input.projectRole); if (!saved) throw new Error("Seul le propriétaire peut attribuer un rôle de projet."); return { saved: true }; }),
  }),
  visits: router({
    save: protectedProcedure.input(z.object({ studyProjectId: z.number().int().positive(), id: z.number().int().positive().optional(), label: z.string().min(2).max(180), visitOrder: z.number().int().min(0), targetDay: z.number().int(), windowBeforeDays: z.number().int().min(0).max(365), windowAfterDays: z.number().int().min(0).max(365), assessments: z.array(z.string().max(240)).max(30), participantStage: z.string().max(120).nullable().optional() })).mutation(async ({ ctx, input }) => { const saved = await db.saveStudyVisit(ctx.user.id, input); if (!saved) throw new Error("Projet introuvable ou accès insuffisant."); return saved; }),
    delete: protectedProcedure.input(z.object({ studyProjectId: z.number().int().positive(), id: z.number().int().positive() })).mutation(async ({ ctx, input }) => { const deleted = await db.deleteStudyVisit(ctx.user.id, input.studyProjectId, input.id); if (!deleted) throw new Error("Visite introuvable ou accès insuffisant."); return { deleted: true }; }),
  }),
  references: router({
    list: protectedProcedure.input(z.object({ studyProjectId: z.number().int().positive() })).query(async ({ ctx, input }) => { const project = await db.getStudyProject(ctx.user.id, input.studyProjectId); if (!project) throw new Error("Projet introuvable ou non autorisé."); return project.references; }),
    versions: protectedProcedure.input(z.object({ studyProjectId: z.number().int().positive(), referenceId: z.number().int().positive() })).query(async ({ ctx, input }) => { const project = await db.getStudyProject(ctx.user.id, input.studyProjectId); if (!project) throw new Error("Projet introuvable ou non autorisé."); return db.listStudyReferenceVersions(ctx.user.id, input.studyProjectId, input.referenceId); }),
    add: protectedProcedure.input(z.object({ studyProjectId: z.number().int().positive(), sectionKey: z.string().min(2).max(80), citation: z.string().min(5).max(4000), sourceUrl: z.string().url().max(1000).nullable().optional(), referenceStatus: z.enum(["VERIFIED", "NEEDS_REVIEW", "OUTDATED", "DRAFT", "ARCHIVED"]), versionLabel: z.string().min(1).max(80), reviewedAt: z.coerce.date().nullable().optional(), changeReason: z.string().min(3).max(600).optional() })).mutation(async ({ ctx, input }) => { const saved = await db.saveStudyReference(ctx.user.id, input); if (saved.forbidden) throw new Error("Projet introuvable ou accès insuffisant."); return saved; }),
    update: protectedProcedure.input(z.object({ studyProjectId: z.number().int().positive(), id: z.number().int().positive(), citation: z.string().min(5).max(4000), sourceUrl: z.string().url().max(1000).nullable().optional(), referenceStatus: z.enum(["VERIFIED", "NEEDS_REVIEW", "OUTDATED", "DRAFT", "ARCHIVED"]), versionLabel: z.string().min(1).max(80), reviewedAt: z.coerce.date().nullable().optional(), changeReason: z.string().min(3).max(600).default("Révision depuis le workspace") })).mutation(async ({ ctx, input }) => { const saved = await db.updateStudyReference(ctx.user.id, input); if (saved.forbidden) throw new Error("Projet introuvable ou accès insuffisant."); return saved; }),
  }),
  methods: router({
    compareDesigns: protectedProcedure.query(() => designOptions),
    sampleSize: protectedProcedure.input(z.object({ studyProjectId: z.number().int().positive(), type: z.enum(["BINARY", "CONTINUOUS", "CLUSTER"]), alpha: z.number().min(0.0001).max(0.2), power: z.number().min(0.5).max(0.999), p1: z.number().min(0).max(1).optional(), p2: z.number().min(0).max(1).optional(), meanDifference: z.number().optional(), sd: z.number().positive().optional(), attrition: z.number().min(0).max(0.95).optional(), allocationRatio: z.number().positive().optional(), clusterSize: z.number().int().positive().optional(), icc: z.number().min(0).max(1).optional() })).mutation(async ({ ctx, input }) => { const { studyProjectId, ...assumptions } = input; const project = await db.getStudyProject(ctx.user.id, studyProjectId); if (!project) throw new Error("Projet introuvable ou non autorisé."); const result = calculateSampleSize(assumptions); await db.saveStudyCalculation(ctx.user.id, studyProjectId, `SAMPLE_SIZE_${input.type}`, assumptions, result, result.warning); return result; }),
    recruitment: protectedProcedure.input(z.object({ studyProjectId: z.number().int().positive(), centers: z.number().int().positive(), monthlyPatientsPerCenter: z.number().min(0), screeningRate: z.number().min(0).max(1), eligibilityRate: z.number().min(0).max(1), consentRate: z.number().min(0).max(1), attritionRate: z.number().min(0).max(0.95), target: z.number().int().positive() })).mutation(async ({ ctx, input }) => { const { studyProjectId, ...assumptions } = input; const project = await db.getStudyProject(ctx.user.id, studyProjectId); if (!project) throw new Error("Projet introuvable ou non autorisé."); const result = forecastRecruitment(assumptions); await db.saveStudyCalculation(ctx.user.id, studyProjectId, "RECRUITMENT_FORECAST", assumptions, result, result.warning); return result; }),
    randomisation: protectedProcedure.input(z.object({ studyProjectId: z.number().int().positive(), ratioA: z.number().int().positive(), ratioB: z.number().int().positive(), blockSize: z.number().int().positive().max(100), totalSlots: z.number().int().min(4).max(1000), stratificationFactors: z.array(z.string().max(120)).max(10).optional(), seed: z.string().min(4).max(200) })).mutation(async ({ ctx, input }) => { const { studyProjectId, ...assumptions } = input; const project = await db.getStudyProject(ctx.user.id, studyProjectId); if (!project) throw new Error("Projet introuvable ou non autorisé."); const result = generateTheoreticalRandomisation(assumptions); await db.saveStudyCalculation(ctx.user.id, studyProjectId, "THEORETICAL_RANDOMISATION", assumptions, result, result.warning); return result; }),
    operationalLoad: protectedProcedure.input(z.object({ studyProjectId: z.number().int().positive(), centers: z.number().int().positive(), coordinatorsPerCenter: z.number().min(0.1), visitsPerParticipant: z.number().int().positive(), targetParticipants: z.number().int().positive(), monthlyCapacityPerCoordinator: z.number().positive(), complexityLevel: z.enum(["LOW", "MEDIUM", "HIGH"]) })).mutation(async ({ ctx, input }) => { const { studyProjectId, ...assumptions } = input; const project = await db.getStudyProject(ctx.user.id, studyProjectId); if (!project) throw new Error("Projet introuvable ou non autorisé."); const result = assessOperationalLoad(assumptions); await db.saveStudyCalculation(ctx.user.id, studyProjectId, "OPERATIONAL_LOAD", assumptions, result, result.warning); return result; }),
    centerCapacity: protectedProcedure.input(z.object({ studyProjectId: z.number().int().positive(), centers: z.number().int().positive(), activatedCenters: z.number().int().min(0), patientsScreenedPerCenterMonth: z.number().min(0), eligibilityRate: z.number().min(0).max(1), consentRate: z.number().min(0).max(1), startUpMonths: z.number().min(0).max(36) })).mutation(async ({ ctx, input }) => { const { studyProjectId, ...assumptions } = input; const project = await db.getStudyProject(ctx.user.id, studyProjectId); if (!project) throw new Error("Projet introuvable ou non autorisé."); const result = assessCenterCapacity(assumptions); await db.saveStudyCalculation(ctx.user.id, studyProjectId, "CENTER_CAPACITY", assumptions, result, result.warning); return result; }),
    protocolComplexity: protectedProcedure.input(z.object({ studyProjectId: z.number().int().positive(), arms: z.number().int().positive(), primaryEndpoints: z.number().int().positive(), visitsPerParticipant: z.number().int().positive(), proceduresPerVisit: z.number().int().min(0), countries: z.number().int().positive(), blinded: z.boolean() })).mutation(async ({ ctx, input }) => { const { studyProjectId, ...assumptions } = input; const project = await db.getStudyProject(ctx.user.id, studyProjectId); if (!project) throw new Error("Projet introuvable ou non autorisé."); const result = scoreProtocolComplexity(assumptions); await db.saveStudyCalculation(ctx.user.id, studyProjectId, "PROTOCOL_COMPLEXITY", assumptions, result, result.warning); return result; }),
    timeline: protectedProcedure.input(z.object({ studyProjectId: z.number().int().positive(), designMonths: z.number().min(0).max(60), feasibilityMonths: z.number().min(0).max(60), regulatoryMonths: z.number().min(0).max(60), activationMonths: z.number().min(0).max(60), recruitmentMonths: z.number().min(0).max(120), treatmentMonths: z.number().min(0).max(120), followUpMonths: z.number().min(0).max(120), analysisMonths: z.number().min(0).max(60), reportingMonths: z.number().min(0).max(60) })).mutation(async ({ ctx, input }) => { const { studyProjectId, ...assumptions } = input; const project = await db.getStudyProject(ctx.user.id, studyProjectId); if (!project) throw new Error("Projet introuvable ou non autorisé."); const result = buildTrialTimeline(assumptions); await db.saveStudyCalculation(ctx.user.id, studyProjectId, "TRIAL_TIMELINE", assumptions, result, result.warning); return result; }),
  }),
});
