import { Toaster } from "@/components/ui/sonner";
import { TooltipProvider } from "@/components/ui/tooltip";
import { lazy, Suspense, type ReactNode } from "react";
import ErrorBoundary from "./components/ErrorBoundary";
import { SeoMeta } from "./components/SeoMeta";
import { ThemeProvider } from "./contexts/ThemeContext";
import { MedicalDisclaimerBanner, CookieConsentBanner } from "./components/LegalBanners";
import { StaticModeNotice } from "./components/StaticModeNotice";
import { RequiresBackend } from "./components/RequiresBackend";
import { Route, Router as WouterRouter, Switch } from "wouter";
const AccountPage = lazy(() => import("./pages/AccountPage"));
const AdminAnalyticsPage = lazy(() => import("./pages/AdminAnalyticsPage"));
const AdminCatalogPage = lazy(() => import("./pages/AdminCatalogPage"));
const AdminPage = lazy(() => import("./pages/AdminPage"));
const ExplorePage = lazy(() => import("./pages/ExplorePage"));
const Home = lazy(() => import("./pages/Home"));
const InfoPage = lazy(() => import("./pages/InfoPage"));
const LearningPage = lazy(() => import("./pages/LearningPage"));
const KnowledgeDashboardPage = lazy(() => import("./pages/KnowledgeDashboardPage"));
const KnowledgeAdminPage = lazy(() => import("./pages/KnowledgeAdminPage"));
const NotFound = lazy(() => import("./pages/NotFound"));
const PrivacySettingsPage = lazy(() => import("./pages/PrivacySettingsPage"));
const ProblemWizard = lazy(() => import("./pages/ProblemWizardStandalone"));
const ResourcesPage = lazy(() => import("./pages/ResourcesPage"));
const ResearchPage = lazy(() => import("./pages/ResearchPage"));
const ToolsPage = lazy(() => import("./pages/ToolsPage"));
const TrialDesignPage = lazy(() => import("./pages/TrialDesignStudio"));
const TrialDesignOperationsPage = lazy(() => import("./pages/TrialToolsLab"));
const AuthorPage = lazy(() => import("./pages/AuthorPage"));
const TrialAuditPage = lazy(() => import("./pages/TrialAuditPage"));
const MaintenancePage = lazy(() => import("./pages/MaintenancePage"));
const DiagnosticsPage = lazy(() => import("./pages/DiagnosticsPage"));
const LegalNoticePage = lazy(() => import("./pages/LegalNoticePage"));
const BackendPage = ({ children }: { children: ReactNode }) => <RequiresBackend>{children}</RequiresBackend>;
const StaticSafeAccountPage = () => <BackendPage><AccountPage /></BackendPage>;
const StaticSafePrivacyPage = () => <BackendPage><PrivacySettingsPage /></BackendPage>;
const StaticSafeAdminPage = () => <BackendPage><AdminPage /></BackendPage>;
const StaticSafeAdminCatalogPage = () => <BackendPage><AdminCatalogPage /></BackendPage>;
const StaticSafeAdminAnalyticsPage = () => <BackendPage><AdminAnalyticsPage /></BackendPage>;
const StaticSafeKnowledgeAdminPage = () => <BackendPage><KnowledgeAdminPage /></BackendPage>;
const StaticSafeContactPage = () => <BackendPage><Contact /></BackendPage>;
const Sources = () => <InfoPage kind="sources" />; const Limits = () => <InfoPage kind="limits" />; const Privacy = () => <InfoPage kind="privacy" />; const Terms = () => <InfoPage kind="terms" />; const How = () => <InfoPage kind="how" />; const About = () => <InfoPage kind="about" />; const Contact = () => <InfoPage kind="contact" />; const Donate = () => <InfoPage kind="donate" />;
function Router() { const base = import.meta.env.BASE_URL.replace(/\/$/, ""); return <WouterRouter base={base}><Suspense fallback={<div className="min-h-screen bg-[#f5f8f7] p-8 text-[#49625f]">Chargement de Clinical Navigator…</div>}><Switch><Route path="/" component={Home} /><Route path="/fr/concevoir-un-essai/outils" component={TrialDesignOperationsPage} /><Route path="/fr/concevoir-un-essai" component={TrialDesignPage} /><Route path="/fr/auditer-un-essai" component={TrialAuditPage} /><Route path="/fr/probleme" component={ProblemWizard} /><Route path="/fr/explorer" component={ExplorePage} /><Route path="/fr/guides" component={ExplorePage} /><Route path="/fr/guides/:slug" component={ExplorePage} /><Route path="/fr/scenarios" component={ExplorePage} /><Route path="/fr/scenarios/:slug" component={ExplorePage} /><Route path="/fr/modules" component={ExplorePage} /><Route path="/fr/modules/:slug" component={ExplorePage} /><Route path="/fr/essais-complexes" component={ExplorePage} /><Route path="/fr/formation" component={LearningPage} /><Route path="/fr/knowledge" component={KnowledgeDashboardPage} /><Route path="/fr/ressources" component={ResourcesPage} /><Route path="/fr/veille" component={ResearchPage} /><Route path="/fr/systeme" component={MaintenancePage} /><Route path="/fr/diagnostic" component={DiagnosticsPage} /><Route path="/fr/outils" component={ToolsPage} /><Route path="/fr/mes-donnees" component={StaticSafePrivacyPage} /><Route path="/fr/mes-cas" component={StaticSafeAccountPage} /><Route path="/fr/favoris" component={StaticSafeAccountPage} /><Route path="/fr/mon-espace" component={StaticSafeAccountPage} /><Route path="/fr/admin/knowledge" component={StaticSafeKnowledgeAdminPage} /><Route path="/fr/admin/donnees" component={StaticSafeAdminAnalyticsPage} /><Route path="/fr/admin/catalogue" component={StaticSafeAdminCatalogPage} /><Route path="/fr/admin" component={StaticSafeAdminPage} /><Route path="/fr/sources" component={Sources} /><Route path="/fr/limites" component={Limits} /><Route path="/fr/confidentialite" component={Privacy} /><Route path="/fr/conditions" component={Terms} /><Route path="/fr/mentions-legales" component={LegalNoticePage} /><Route path="/fr/comment-ca-marche" component={How} /><Route path="/fr/a-propos" component={About} /><Route path="/fr/auteur" component={AuthorPage} /><Route path="/fr/contact" component={StaticSafeContactPage} /><Route path="/fr/soutenir" component={Donate} /><Route path="/404" component={NotFound} /><Route component={NotFound} /></Switch></Suspense></WouterRouter>; }
export default function App() { return <ErrorBoundary><ThemeProvider defaultTheme="system" switchable><TooltipProvider><SeoMeta /><Toaster /><MedicalDisclaimerBanner /><CookieConsentBanner /><StaticModeNotice /><Router /></TooltipProvider></ThemeProvider></ErrorBoundary>; }
