import { ClinicalShell } from "@/components/ClinicalShell";
import { Button } from "@/components/ui/button";
import { ArrowRight, Award, BookOpenCheck, BriefcaseBusiness, Code2, Coffee, ExternalLink, GraduationCap, HeartHandshake, ShieldCheck } from "lucide-react";
import { Link } from "wouter";

const skills = [
  ["Recherche clinique", "Coordination multicentrique, monitoring, données, documentation investigateur, formation et qualité."],
  ["Méthodologie", "Conception d’essais, Step-Wedge, endpoints, estimands, qualité par la conception et workflows opérationnels."],
  ["Réglementaire", "Expérience autour des soumissions, CPP/éthique, CNIL/RGPD, ANSM et documentation de recherche."],
  ["IA & numérique", "Ingénierie IA, full-stack, automatisation, systèmes de connaissance, applications cliniques et data."],
  ["Cloud & IT", "Java, Python, JavaScript, bases de données, cloud, eCRF, outils de données et AWS."],
  ["Gestion de projet", "Coordination, planification, formation, négociation, budget, opérations et pilotage transversal."],
];

export default function AuthorPage(){return <ClinicalShell><section className="border-b border-[#dce9e4] bg-[#edf5f1]"><div className="container py-12"><p className="text-xs font-bold uppercase tracking-[0.16em] text-[#39806f]">Créateur du projet</p><h1 className="mt-3 font-serif text-5xl font-bold tracking-tight text-[#0d2b36]">Kevin HOUNSINOU</h1><p className="mt-4 max-w-3xl text-lg leading-8 text-[#526b67]">Clinical Research Coordinator · Ingénierie IA · Développement full-stack · Conception de solutions numériques pour la recherche clinique</p><div className="mt-6 flex flex-wrap gap-3"><Link href="/fr/concevoir-un-essai"><Button className="bg-[#0d2b36]">Découvrir Clinical Navigator <ArrowRight className="ml-2 h-4 w-4"/></Button></Link><a href="https://github.com/Kevingiscard/Clinical-Navigator" target="_blank" rel="noreferrer"><Button variant="outline" className="border-[#b9d7cd]"><Code2 className="mr-2 h-4 w-4"/>Code source GitHub <ExternalLink className="ml-2 h-3.5 w-3.5"/></Button></a></div></div></section>
<section className="container grid gap-8 py-12 lg:grid-cols-[1.1fr_0.9fr]"><article className="rounded-2xl border border-[#dbe8e3] bg-white p-8 shadow-sm"><p className="text-xs font-bold uppercase tracking-[0.15em] text-[#39806f]">Parcours</p><h2 className="mt-2 font-serif text-3xl font-bold text-[#153e43]">Un projet né à l’intersection de la clinique, de la donnée et de l’ingénierie.</h2><div className="mt-6 space-y-4 text-[#526c67] leading-7"><p>Clinical Navigator est construit à partir d’une expérience professionnelle en recherche clinique et d’un profil hybride associant coordination d’études, réglementation, qualité, gestion de projet et développement logiciel.</p><p>Le projet cherche à rendre les connaissances de la recherche clinique plus navigables : comprendre une situation, construire un essai, vérifier les cohérences, retrouver les bonnes références et transformer une question complexe en actions documentées.</p><p>La plateforme a été pensée pour rester portable, versionnée et transparente sur ses limites, afin de ne pas confondre assistance numérique et validation scientifique ou réglementaire.</p></div></article><aside className="rounded-2xl bg-[#0d2b36] p-8 text-white"><BriefcaseBusiness className="h-7 w-7 text-[#a8d9c7]"/><h2 className="mt-4 font-serif text-2xl font-bold">Expérience & domaines</h2><div className="mt-5 grid gap-3 text-sm">{['Coordination en recherche clinique','Études multicentriques en oncologie','Monitoring & data management','Réglementaire, qualité & RGPD','IA, full-stack & cloud','Gestion de projet'].map(x=><div key={x} className="flex items-start gap-2"><ShieldCheck className="mt-0.5 h-4 w-4 text-[#a8d9c7]"/>{x}</div>)}</div></aside></section>
<section className="bg-white border-y border-[#dbe8e3]"><div className="container py-12"><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{skills.map(([title,text])=><article key={title} className="rounded-2xl border border-[#dbe8e3] bg-[#f7fbf9] p-6"><h3 className="font-bold text-[#173f43]">{title}</h3><p className="mt-2 text-sm leading-6 text-[#607771]">{text}</p></article>)}</div></div></section>
<section className="container py-12"><div className="grid gap-6 md:grid-cols-3"><article className="rounded-2xl border border-[#dbe8e3] bg-white p-6"><GraduationCap className="h-6 w-6 text-[#2a8171]"/><h3 className="mt-4 font-bold text-[#173e43]">Formation & certifications</h3><p className="mt-2 text-sm leading-6 text-[#607771]">Diplôme en droit de la diplomatie, développement full-stack, AWS Cloud Practitioner, Scrum Master et certification ICH E6(R3) / Good Clinical Practice.</p></article><article className="rounded-2xl border border-[#dbe8e3] bg-white p-6"><Award className="h-6 w-6 text-[#2a8171]"/><h3 className="mt-4 font-bold text-[#173e43]">Approche</h3><p className="mt-2 text-sm leading-6 text-[#607771]">Privilégier les sources vérifiables, les hypothèses explicites, les calculs transparents, le versioning et la revue humaine lorsque la décision est critique.</p></article><article className="rounded-2xl border border-[#dbe8e3] bg-white p-6"><BookOpenCheck className="h-6 w-6 text-[#2a8171]"/><h3 className="mt-4 font-bold text-[#173e43]">Références</h3><p className="mt-2 text-sm leading-6 text-[#607771]">Clinical Navigator s’appuie notamment sur ICH E8(R1), E9/E9(R1), E6(R3), SPIRIT 2025, CONSORT 2025, OMS, EMA/CTIS et les sources nationales pertinentes.</p><Link href="/fr/veille" className="mt-4 inline-flex text-sm font-bold text-[#1c7566]">Voir les références <ArrowRight className="ml-1 h-4 w-4"/></Link></article></div></section>
<section className="container pb-16"><div className="rounded-[2rem] bg-[#0d2b36] p-8 text-center text-white"><HeartHandshake className="mx-auto h-7 w-7 text-[#a6d6c6]"/><h2 className="mt-4 font-serif text-3xl font-bold">Soutenir Clinical Navigator</h2><p className="mx-auto mt-3 max-w-2xl text-[#c7ddd7]">Le projet est conçu comme une plateforme utile, indépendante et portable. Un soutien contribue à financer la maintenance, la documentation et les évolutions méthodologiques.</p><a href="mailto:kevingiscard@outlook.com?subject=Soutien%20Clinical%20Navigator%20%E2%80%94%20offrir%20un%20caf%C3%A9" className="mt-6 inline-flex"><Button className="bg-[#b8dfce] text-[#0d2b36] hover:bg-white"><Coffee className="mr-2 h-4 w-4"/>Offrir un café au créateur</Button></a></div></section></ClinicalShell>}
