import { useMemo, useState } from "react";
import { ClinicalShell } from "@/components/ClinicalShell";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { knowledgeItems, clinicalKnowledgeGraph, knowledgeStats } from "@shared/knowledgeDatasets";
import { ExternalLink, GitBranch, Search, ShieldAlert } from "lucide-react";

export default function KnowledgeDashboardPage() {
  const [query, setQuery] = useState("");
  const [status, setStatus] = useState("ALL");
  const filtered = useMemo(() => knowledgeItems.filter(item => { const text = `${item.title} ${item.shortDescription} ${item.keywords.join(" ")}`.toLowerCase(); return (!query || text.includes(query.toLowerCase())) && (status === "ALL" || item.status === status); }).slice(0, 24), [query, status]);
  return <ClinicalShell><main className="container max-w-7xl py-8">
    <header className="border-b border-border pb-6"><p className="text-xs font-semibold uppercase tracking-[0.12em] text-muted-foreground">Knowledge Core · version 1.0.0</p><h1 className="mt-2 text-3xl font-semibold tracking-tight">Clinical Knowledge Dashboard</h1><p className="mt-3 max-w-3xl text-sm leading-6 text-muted-foreground">Une vue calculée du graphe de connaissances. Les chiffres proviennent des fiches embarquées ; un statut `NEEDS_REVIEW` n’est pas une validation réglementaire.</p></header>
    <section className="mt-6 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{[["Fiches", knowledgeStats.total], ["Sources distinctes", knowledgeStats.sources], ["Juridictions indexées", knowledgeStats.jurisdictions], ["Relations", knowledgeStats.relations]].map(([label, value]) => <article key={label as string} className="rounded-lg border border-border bg-card p-4"><p className="text-xs font-semibold uppercase tracking-wide text-muted-foreground">{label}</p><p className="mt-2 text-2xl font-semibold">{value}</p></article>)}</section>
    <section className="mt-6 grid gap-3 sm:grid-cols-3"><div className="rounded-lg border border-border bg-card p-4"><p className="text-xs text-muted-foreground">Verified</p><p className="mt-1 font-semibold">{knowledgeStats.verified}</p></div><div className="rounded-lg border border-border bg-card p-4"><p className="text-xs text-muted-foreground">Needs review</p><p className="mt-1 font-semibold">{knowledgeStats.needsReview}</p></div><div className="rounded-lg border border-border bg-card p-4"><p className="text-xs text-muted-foreground">Offline available</p><p className="mt-1 font-semibold">{knowledgeStats.offlineAvailable}</p></div></section>
    <section className="mt-8 rounded-lg border border-border bg-card p-5"><div className="flex flex-wrap gap-3"><div className="relative min-w-[240px] flex-1"><Search className="pointer-events-none absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-foreground" /><Input aria-label="Rechercher dans la base de connaissances" value={query} onChange={event => setQuery(event.target.value)} placeholder="Endpoint, estimand, consentement…" className="pl-9" /></div>{["ALL", "VERIFIED", "NEEDS_REVIEW", "DRAFT"].map(value => <Button key={value} type="button" variant={status === value ? "default" : "outline"} size="sm" onClick={() => setStatus(value)}>{value === "ALL" ? "Toutes" : value}</Button>)}</div><p className="mt-4 text-xs text-muted-foreground">{filtered.length} fiches affichées sur {knowledgeStats.total}. Recherche locale, sans envoi réseau.</p><div className="mt-4 grid gap-3 md:grid-cols-2">{filtered.map(item => <article key={item.id} className="rounded-lg border border-border p-4"><div className="flex items-start justify-between gap-3"><div><p className="text-xs font-semibold uppercase tracking-wide text-muted-foreground">{item.type} · {item.category}</p><h2 className="mt-1 font-semibold">{item.title}</h2></div><Badge variant="outline">{item.status}</Badge></div><p className="mt-2 text-sm leading-6 text-muted-foreground">{item.shortDescription}</p><div className="mt-3 flex flex-wrap gap-2 text-xs text-muted-foreground"><span>v{item.version}</span><span>·</span><span>{item.offlineAvailable ? "offline" : "online"}</span>{item.sources[0]?.url && <a className="inline-flex items-center gap-1 underline" href={item.sources[0].url} target="_blank" rel="noreferrer" aria-label={`Ouvrir la source de ${item.title} dans un nouvel onglet`}>Source <ExternalLink className="h-3 w-3" /></a>}</div></article>)}{!filtered.length && <div className="rounded-lg border border-dashed border-border p-8 text-center text-sm text-muted-foreground"><ShieldAlert className="mx-auto h-5 w-5" /><p className="mt-2">Aucune fiche ne correspond à la recherche.</p></div>}</div></section>
    <section className="mt-8 rounded-lg border border-border bg-card p-5"><div className="flex items-center gap-2"><GitBranch className="h-4 w-4" /><h2 className="font-semibold">Relations principales</h2></div><div className="mt-4 grid gap-2 md:grid-cols-2">{clinicalKnowledgeGraph.map(relation => <div key={relation.id} className="rounded-md border border-border px-3 py-2 text-sm"><span className="font-mono text-xs">{relation.from}</span><span className="mx-2 text-muted-foreground">— {relation.type} →</span><span className="font-mono text-xs">{relation.to}</span><p className="mt-1 text-xs text-muted-foreground">Statut : {relation.status} · revue humaine requise</p></div>)}</div></section>
  </main></ClinicalShell>;
}
