import { ClinicalShell } from "@/components/ClinicalShell";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { knowledgeItems, knowledgeStats } from "@shared/knowledgeDatasets";
import { ShieldCheck } from "lucide-react";

export default function KnowledgeAdminPage() {
  const reviewQueue = knowledgeItems.filter(item => item.status === "NEEDS_REVIEW").slice(0, 30);
  return <ClinicalShell><main className="container max-w-7xl py-8"><header className="border-b border-border pb-6"><p className="text-xs font-semibold uppercase tracking-wide text-muted-foreground">Administration · Knowledge</p><h1 className="mt-2 text-3xl font-semibold">Review Queue</h1><p className="mt-3 max-w-3xl text-sm leading-6 text-muted-foreground">Cette vue prépare une revue humaine. Elle ne publie jamais automatiquement une modification réglementaire détectée.</p></header><section className="mt-6 grid gap-3 sm:grid-cols-4">{[["À revoir", knowledgeStats.needsReview], ["Verified", knowledgeStats.verified], ["Relations", knowledgeStats.relations], ["Sources", knowledgeStats.sources]].map(([label, value]) => <div key={label as string} className="rounded-lg border border-border bg-card p-4"><p className="text-xs text-muted-foreground">{label}</p><p className="mt-1 text-xl font-semibold">{value}</p></div>)}</section><section className="mt-8 rounded-lg border border-border bg-card p-5"><div className="flex items-center justify-between gap-3"><div className="flex items-center gap-2"><ShieldCheck className="h-4 w-4" /><h2 className="font-semibold">Éléments nécessitant une revue</h2></div><Button type="button" variant="outline" size="sm" disabled>Publier après revue</Button></div><div className="mt-4 divide-y divide-border">{reviewQueue.map(item => <article key={item.id} className="grid gap-2 py-4 md:grid-cols-[1fr_auto] md:items-center"><div><p className="font-mono text-xs text-muted-foreground">{item.id} · v{item.version}</p><h3 className="mt-1 font-semibold">{item.title}</h3><p className="mt-1 text-sm text-muted-foreground">{item.shortDescription}</p><p className="mt-2 text-xs text-muted-foreground">Source : {item.sources.map(source => source.title).join(", ")} · Dernière revue : {item.verifiedAt ?? "non vérifiée"}</p></div><Badge variant="outline">{item.status}</Badge></article>)}</div></section></main></ClinicalShell>;
}
