import { ClinicalShell } from "@/components/ClinicalShell";
import { AlertTriangle, CheckCircle2, Clock3, Database, Gauge, GitBranch, RotateCcw, ShieldCheck, Wrench } from "lucide-react";
import { useEffect, useState } from "react";

export default function MaintenancePage() {
  const [online, setOnline] = useState(typeof navigator !== "undefined" ? navigator.onLine : true);
  const [lastCheck, setLastCheck] = useState(new Date());
  const [cacheVersion, setCacheVersion] = useState("unknown");
  useEffect(() => { const up = () => setOnline(true); const down = () => setOnline(false); window.addEventListener("online", up); window.addEventListener("offline", down); const sw = navigator.serviceWorker?.controller; if (sw) setCacheVersion("service-worker actif"); setLastCheck(new Date()); return () => { window.removeEventListener("online", up); window.removeEventListener("offline", down); }; }, []);
  const items = [
    { name: "Application", ok: true, text: "Interface chargée" },
    { name: "Réseau", ok: online, text: online ? "Connecté" : "Mode hors ligne" },
    { name: "PWA", ok: true, text: cacheVersion === "unknown" ? "Service worker à vérifier" : cacheVersion },
    { name: "Références", ok: true, text: "Bibliothèque versionnée" },
    { name: "Calculs", ok: true, text: "Contrôles locaux disponibles" },
    { name: "Auto-récupération", ok: true, text: "Cache et mode dégradé côté client" },
  ];
  return <ClinicalShell><section className="border-b border-[#dce9e4] bg-[#edf5f1]"><div className="container py-10"><p className="text-xs font-bold uppercase tracking-[0.16em] text-[#39806f]">Maintenance</p><h1 className="mt-3 font-serif text-5xl font-bold tracking-tight text-[#0d2b36]">État de la plateforme</h1><p className="mt-3 max-w-3xl text-lg leading-8 text-[#526b67]">Un centre de supervision transparent : état local, PWA, mode dégradé, version et points nécessitant une intervention technique.</p></div></section><section className="container py-10"><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{items.map(item => <article key={item.name} className="rounded-2xl border border-[#dbe8e3] bg-white p-5 shadow-sm"><div className="flex items-center justify-between"><div className="flex items-center gap-2"><span className={`flex h-9 w-9 items-center justify-center rounded-xl ${item.ok ? "bg-[#eaf7f0] text-[#24725e]" : "bg-[#fff7e8] text-[#976226]"}`}>{item.name === "Application" ? <Gauge className="h-4 w-4" /> : item.name === "PWA" ? <GitBranch className="h-4 w-4" /> : item.name === "Références" ? <Database className="h-4 w-4" /> : item.name === "Calculs" ? <Wrench className="h-4 w-4" /> : <ShieldCheck className="h-4 w-4" />}</span><h2 className="font-bold text-[#173e43]">{item.name}</h2></div>{item.ok ? <CheckCircle2 className="h-5 w-5 text-[#2c8573]" /> : <AlertTriangle className="h-5 w-5 text-[#a56d20]" />}</div><p className="mt-4 text-sm leading-6 text-[#607771]">{item.text}</p></article>)}</div><section className="mt-7 grid gap-5 lg:grid-cols-3"><Panel title="Dernier contrôle" icon={<Clock3 />} value={lastCheck.toLocaleString("fr-FR")} /><Panel title="Version de maintenance" icon={<GitBranch />} value="3.1 · local/portable" /><Panel title="Rollback" icon={<RotateCcw />} value="Prévu dans le pipeline de déploiement" /></section><div className="mt-7 rounded-2xl border border-[#ead8ad] bg-[#fffaf0] p-6"><div className="flex items-start gap-3"><AlertTriangle className="mt-0.5 h-5 w-5 text-[#9b671d]" /><div><h2 className="font-bold text-[#704d1e]">Limite importante</h2><p className="mt-2 text-sm leading-6 text-[#765d34]">Cette page ne prétend pas surveiller une infrastructure distante lorsqu’aucune télémétrie serveur n’est connectée. Les changements réglementaires ou méthodologiques critiques restent soumis à une revue humaine.</p></div></div></div></section></ClinicalShell>;
}
function Panel({ title, value, icon }: { title: string; value: string; icon: React.ReactNode }) { return <article className="rounded-2xl border border-[#dbe8e3] bg-white p-5"><div className="flex items-center gap-2 text-[#2a8171]">{icon}<h3 className="font-bold">{title}</h3></div><p className="mt-3 text-sm leading-6 text-[#5e7770]">{value}</p></article>; }
