import { ArrowLeft, ArrowRight, Bot, CheckCircle2, ChevronRight, CircleHelp, Download, Filter, RotateCcw, Search, ShieldCheck } from "lucide-react";
import { useMemo, useState } from "react";
import { Link, useRoute } from "wouter";
import { Input } from "@/components/ui/input";
import { ResourceCard } from "@/components/ResourceCard";
import { answerOffline } from "@/lib/offlineAI";
import { ClinicalShell } from "@/components/ClinicalShell";
import { getModuleDefinition, getModuleResources, getModuleResource, moduleDefinitions, moduleResourceStats, type ModuleResource, type ModuleResourceType } from "@shared/moduleResources";

const ALL = "__all__";
const typeLabels: Record<ModuleResourceType, string> = { GUIDE: "Guide", TOOL: "Outil", CHECKLIST: "Checklist", TEMPLATE: "Modèle", SOURCE: "Source", TRAINING: "Formation", EXAMPLE: "Exemple", CASE_STUDY: "Cas", CALCULATOR: "Calculateur", FAQ: "FAQ", DOCUMENTATION: "Documentation" };
const aliases: Record<string, string> = { sources: "ressources", "essais-complexes": "step-wedge", outils: "conception" };

export default function ModuleHubPage() {
  const [, params] = useRoute("/fr/modules/:slug");
  const requestedSlug = params?.slug ?? "conception";
  const moduleId = aliases[requestedSlug] ?? requestedSlug;
  const module = getModuleDefinition(moduleId) ?? getModuleDefinition("conception")!;
  const sourceResources = getModuleResources(module.id);
  const [query, setQuery] = useState("");
  const [type, setType] = useState(ALL);
  const [level, setLevel] = useState(ALL);
  const [audience, setAudience] = useState(ALL);
  const [jurisdiction, setJurisdiction] = useState(ALL);
  const [currentStep, setCurrentStep] = useState(0);
  const [aiQuery, setAiQuery] = useState("");
  const [aiAnswer, setAiAnswer] = useState<ReturnType<typeof answerOffline> | null>(null);
  const [checked, setChecked] = useState<Record<string, boolean>>(() => { try { return JSON.parse(localStorage.getItem(`cn-module-checklist-${module.id}`) || "{}"); } catch { return {}; } });
  const step = module.steps[currentStep] ?? module.steps[0];
  const filtered = useMemo(() => sourceResources.filter(resource => {
    const haystack = `${resource.title} ${resource.description} ${resource.tags.join(" ")}`.toLocaleLowerCase();
    return (!query || haystack.includes(query.toLocaleLowerCase())) && (type === ALL || resource.type === type) && (level === ALL || resource.level === level) && (audience === ALL || resource.audience.includes(audience)) && (jurisdiction === ALL || resource.jurisdiction.includes(jurisdiction));
  }), [sourceResources, query, type, level, audience, jurisdiction]);
  const related = module.relatedModules.map(getModuleDefinition).filter((item): item is NonNullable<typeof item> => Boolean(item)).slice(0, 4);
  const currentResourceIds = Array.from(new Set([...(step?.resourceIds ?? []), ...(step?.toolIds ?? []), ...(step?.checklistIds ?? [])]));
  const currentResources = currentResourceIds.map(getModuleResource).filter(Boolean) as ModuleResource[];
  const checklistResources = sourceResources.filter(resource => resource.type === "CHECKLIST");
  const checkedCount = checklistResources.filter(resource => checked[resource.id]).length;
  const aiResources = useMemo(() => {
    const normalized = aiQuery.toLocaleLowerCase();
    const matches = sourceResources.filter(resource => `${resource.title} ${resource.description} ${resource.tags.join(" ")}`.toLocaleLowerCase().includes(normalized));
    return (matches.length ? matches : sourceResources).slice(0, 5);
  }, [aiQuery, sourceResources]);
  const updateCheck = (id: string, value: boolean) => { const next = { ...checked, [id]: value }; setChecked(next); localStorage.setItem(`cn-module-checklist-${module.id}`, JSON.stringify(next)); };
  const reset = () => { setQuery(""); setType(ALL); setLevel(ALL); setAudience(ALL); setJurisdiction(ALL); };
  const exportChecklist = () => { const payload = { application: "Clinical Navigator", module: module.id, exportedAt: new Date().toISOString(), checklist: checklistResources.map(resource => ({ id: resource.id, title: resource.title, completed: Boolean(checked[resource.id]) })) }; const url = URL.createObjectURL(new Blob([JSON.stringify(payload, null, 2)], { type: "application/json" })); const anchor = document.createElement("a"); anchor.href = url; anchor.download = `${module.slug}-checklist.json`; anchor.click(); URL.revokeObjectURL(url); };
  const runAi = () => setAiAnswer(answerOffline(aiQuery || `ressources ${module.title}`, "fr"));

  return <ClinicalShell>
    <section className="border-b border-[#d9e0de] bg-[#f1f3f2]"><div className="container py-8">
      <Link href="/fr/modules" className="inline-flex items-center gap-2 text-sm font-bold text-[#304946]"><ArrowLeft className="h-4 w-4" />Tous les modules</Link>
      <div className="mt-6 flex flex-wrap items-end justify-between gap-5"><div className="max-w-4xl"><p className="text-xs font-bold uppercase tracking-[0.16em] text-[#536662]">Centre de travail · module {module.version}</p><h1 className="mt-2 text-4xl font-bold tracking-tight text-[#142523] sm:text-5xl">{requestedSlug === "essais-complexes" ? "Essais complexes" : module.title}</h1><p className="mt-3 max-w-3xl text-lg leading-8 text-[#52625f]">{module.description} Un hub opérationnel pour comprendre, commencer, documenter, revoir et continuer sans données patient.</p></div><div className="rounded-xl border border-[#d6dfdc] bg-white px-4 py-3 text-sm text-[#4c5d5a]"><p className="font-bold">{module.status === "VERIFIED" ? "Contenu vérifié pour son périmètre" : "Revue humaine requise"}</p><p className="mt-1">Mis à jour le {module.lastUpdated} · prochaine revue {module.nextReview}</p></div></div>
      <div className="mt-6 flex flex-wrap gap-2">{module.audiences.slice(0, 6).map(item => <span key={item} className="rounded-full border border-[#d1dbd8] bg-white px-3 py-1.5 text-xs font-semibold text-[#52635f]">{item}</span>)}</div>
    </div></section>

    <main className="container py-8">
      <section className="grid gap-5 lg:grid-cols-[minmax(0,1fr)_300px]"><div className="rounded-2xl border border-[#dce4e1] bg-white p-5 shadow-sm sm:p-7"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-[0.14em] text-[#536662]">Par où commencer ?</p><h2 className="mt-2 text-2xl font-bold text-[#172c2d]">Parcours recommandé</h2><p className="mt-2 max-w-2xl text-sm leading-6 text-[#5d6e6a]">Chaque étape est cliquable. Le contenu reste pédagogique : vérifiez le protocole, les SOP, les autorités et les rôles compétents.</p></div><span className="rounded-full bg-[#eef1f0] px-3 py-1.5 text-xs font-bold text-[#435451]">Vous êtes ici · {currentStep + 1}/{module.steps.length}</span></div><div className="mt-6 grid gap-2 sm:grid-cols-2">{module.steps.map((item, index) => <button type="button" key={item.id} onClick={() => setCurrentStep(index)} className={`flex items-start gap-3 rounded-xl border p-3 text-left transition ${index === currentStep ? "border-[#60746f] bg-[#f3f5f4]" : "border-[#e3e9e7] hover:border-[#aebcb8]"}`}><span className={`mt-0.5 flex h-6 w-6 shrink-0 items-center justify-center rounded-full text-xs font-bold ${index <= currentStep ? "bg-[#283c39] text-white" : "bg-[#edf1ef] text-[#65736f]"}`}>{index + 1}</span><span><span className="block font-bold text-[#263836]">{item.title}</span><span className="mt-1 block text-xs leading-5 text-[#687773]">{item.description}</span></span></button>)}</div></div><aside className="rounded-2xl bg-[#283c39] p-6 text-white"><p className="text-xs font-bold uppercase tracking-[0.14em] text-[#d7e2df]">Objectif du module</p><div className="mt-4 grid gap-3">{module.objectives.map(objective => <p key={objective} className="flex gap-2 text-sm leading-6 text-[#f0f4f3]"><CheckCircle2 className="mt-1 h-4 w-4 shrink-0 text-[#d7e2df]" />{objective}</p>)}</div><div className="mt-6 border-t border-white/20 pt-5"><p className="text-xs font-bold uppercase tracking-[0.14em] text-[#d7e2df]">Prérequis</p>{module.prerequisites.slice(0, 3).map(item => <p key={item} className="mt-2 text-xs leading-5 text-[#e1e9e6]">{item}</p>)}</div></aside></section>

      <section className="mt-6 rounded-2xl border border-[#dce4e1] bg-white p-5 shadow-sm sm:p-7"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-[0.14em] text-[#536662]">Étape active · {step.order}</p><h2 className="mt-2 text-2xl font-bold text-[#172c2d]">{step.title}</h2><p className="mt-2 max-w-3xl text-sm leading-6 text-[#5d6e6a]">{step.description}</p></div><div className="flex gap-2"><button type="button" className="inline-flex items-center gap-1 rounded-lg border border-[#d3ddda] px-3 py-2 text-xs font-bold text-[#435451] disabled:opacity-40" disabled={currentStep === 0} onClick={() => setCurrentStep(Math.max(0, currentStep - 1))}><ArrowLeft className="h-3.5 w-3.5" />Précédent</button><button type="button" className="inline-flex items-center gap-1 rounded-lg bg-[#283c39] px-3 py-2 text-xs font-bold text-white disabled:opacity-40" disabled={currentStep === module.steps.length - 1} onClick={() => setCurrentStep(Math.min(module.steps.length - 1, currentStep + 1))}>Suivant<ArrowRight className="h-3.5 w-3.5" /></button></div></div><div className="mt-5 grid gap-3 sm:grid-cols-3">{step.objectives.map(objective => <div key={objective} className="rounded-xl bg-[#f4f6f5] p-4 text-sm leading-6 text-[#4f615d]"><CheckCircle2 className="mb-2 h-4 w-4 text-[#3d504c]" />{objective}</div>)}</div>{currentResources.length > 0 && <div className="mt-6"><h3 className="text-sm font-bold uppercase tracking-wide text-[#536662]">Ressources de cette étape</h3><div className="mt-3 grid gap-3 md:grid-cols-2">{currentResources.slice(0, 4).map(resource => <ResourceCard key={resource.id} resource={resource} compact />)}</div></div>}</section>

      <section className="mt-6 rounded-2xl border border-[#dce4e1] bg-white p-5 shadow-sm sm:p-7"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-[0.14em] text-[#536662]">Recherche dans ce module</p><h2 className="mt-2 text-2xl font-bold text-[#172c2d]">Trouver une ressource</h2></div><button type="button" onClick={reset} className="inline-flex items-center gap-2 text-xs font-bold text-[#4b5e5a]"><RotateCcw className="h-3.5 w-3.5" />Réinitialiser</button></div><div className="mt-5 grid gap-3 lg:grid-cols-[minmax(0,1fr)_repeat(4,minmax(0,150px))]"><label className="relative"><Search className="absolute left-3 top-3 h-4 w-4 text-[#71807d]" /><Input aria-label="Rechercher dans ce module" value={query} onChange={event => setQuery(event.target.value)} placeholder="Estimand, protocole, CAPA…" className="border-[#d3ddda] pl-9" /></label><FilterSelect label="Type" value={type} onChange={setType} options={[ALL, ...Object.keys(typeLabels)]} /><FilterSelect label="Niveau" value={level} onChange={setLevel} options={[ALL, "Débutant", "Intermédiaire", "Avancé", "Expert"]} /><FilterSelect label="Public" value={audience} onChange={setAudience} options={[ALL, "Investigateur", "ARC / CRA", "Chef de projet", "Data Manager", "Biostatisticien", "Regulatory", "QA", "Étudiant"]} /><FilterSelect label="Juridiction" value={jurisdiction} onChange={setJurisdiction} options={[ALL, "International", "France", "Union européenne", "Bénin", "Afrique", "États-Unis"]} /></div><div className="mt-5 flex items-center gap-2 text-xs text-[#64736f]"><Filter className="h-3.5 w-3.5" />{filtered.length} ressource{filtered.length > 1 ? "s" : ""} pertinente{filtered.length > 1 ? "s" : ""} sur {sourceResources.length}</div><div className="mt-4 grid gap-4 md:grid-cols-2 xl:grid-cols-3">{filtered.map(resource => <ResourceCard key={resource.id} resource={resource} />)}</div>{filtered.length === 0 && <div className="mt-4 rounded-xl border border-dashed border-[#b9c7c3] bg-[#f5f7f6] p-6 text-center text-sm text-[#596a66]">Ressources en cours de vérification ou aucun résultat pour ces filtres. Réduisez les filtres ou consultez le module Ressources.</div>}</section>

      <section className="mt-6 grid gap-6 lg:grid-cols-2"><div className="rounded-2xl border border-[#dce4e1] bg-white p-5 shadow-sm sm:p-7"><div className="flex items-start justify-between gap-3"><div><p className="text-xs font-bold uppercase tracking-[0.14em] text-[#536662]">Checklist locale</p><h2 className="mt-2 text-2xl font-bold text-[#172c2d]">Préparer et suivre</h2></div><div className="text-right"><p className="text-2xl font-bold text-[#263c38]">{checkedCount}/{checklistResources.length}</p><p className="text-xs text-[#697975]">terminées</p></div></div>{checklistResources.length ? <div className="mt-5 grid gap-3">{checklistResources.map(resource => <label key={resource.id} className="flex cursor-pointer items-start gap-3 rounded-lg border border-[#e4eae8] p-3 text-sm text-[#4c5d59]"><input type="checkbox" checked={Boolean(checked[resource.id])} onChange={event => updateCheck(resource.id, event.target.checked)} className="mt-1 h-4 w-4 accent-[#283c39]" /><span><span className="block font-bold text-[#283c39]">{resource.title}</span><span className="mt-1 block text-xs leading-5">{resource.description}</span></span></label>)}</div> : <p className="mt-5 text-sm text-[#697975]">Ressources en cours de vérification.</p>}<div className="mt-5 flex flex-wrap gap-2"><button type="button" onClick={exportChecklist} className="inline-flex items-center gap-2 rounded-lg border border-[#d3ddda] px-3 py-2 text-xs font-bold text-[#3e514d]"><Download className="h-3.5 w-3.5" />Exporter localement</button><button type="button" onClick={() => { setChecked({}); localStorage.removeItem(`cn-module-checklist-${module.id}`); }} className="inline-flex items-center gap-2 rounded-lg border border-[#d3ddda] px-3 py-2 text-xs font-bold text-[#3e514d]"><RotateCcw className="h-3.5 w-3.5" />Réinitialiser</button></div></div>

      <div className="rounded-2xl border border-[#dce4e1] bg-white p-5 shadow-sm sm:p-7"><div className="flex items-start gap-3"><div className="rounded-lg bg-[#eef1f0] p-2"><Bot className="h-5 w-5 text-[#354945]" /></div><div><p className="text-xs font-bold uppercase tracking-[0.14em] text-[#536662]">Clinical Navigator AI</p><h2 className="mt-2 text-2xl font-bold text-[#172c2d]">Être orienté hors connexion</h2></div></div><p className="mt-3 text-sm leading-6 text-[#5d6e6a]">Le moteur local ne produit pas une décision clinique ou réglementaire. Il recherche dans le guide embarqué et propose des ressources cliquables.</p><div className="mt-4 flex gap-2"><Input aria-label="Demander une orientation dans ce module" value={aiQuery} onChange={event => setAiQuery(event.target.value)} onKeyDown={event => { if (event.key === "Enter") runAi(); }} placeholder="Ex. Comment faire un SAP ?" /><button type="button" onClick={runAi} className="rounded-lg bg-[#283c39] px-4 py-2 text-sm font-bold text-white">Orienter</button></div>{aiAnswer && <div className="mt-4 rounded-xl bg-[#f4f6f5] p-4"><div className="flex items-center gap-2 text-xs font-bold uppercase tracking-wide text-[#4c5e5a]"><ShieldCheck className="h-3.5 w-3.5" />Réponse hors connexion · confiance indicative {Math.round(aiAnswer.confidence * 100)}%</div><p className="mt-3 whitespace-pre-line text-sm leading-6 text-[#4f605c]">{aiAnswer.text}</p><div className="mt-4 grid gap-2">{aiResources.map(resource => <ResourceCard key={resource.id} resource={resource} compact />)}</div></div>}<p className="mt-4 text-xs leading-5 text-[#77837f]">Ne saisissez aucune donnée patient. Les liens externes nécessitent Internet. Les juridictions non confirmées restent à revoir.</p></div></section>

      <section className="mt-6 rounded-2xl border border-[#dce4e1] bg-[#f4f6f5] p-5 sm:p-7"><div className="flex items-center gap-2 text-xs font-bold uppercase tracking-[0.14em] text-[#536662]"><CircleHelp className="h-4 w-4" />Continuer dans Clinical Navigator</div><div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{related.map(item => <Link key={item.id} href={`/fr/modules/${item.slug}`} className="flex items-center justify-between rounded-xl bg-white p-4 text-sm font-bold text-[#283c39] shadow-sm hover:ring-1 hover:ring-[#9daaa7]"><span>{item.title}</span><ChevronRight className="h-4 w-4" /></Link>)}</div></section>
      <p className="mt-6 text-xs leading-5 text-[#77837f]">Version {module.version} · dernière mise à jour {module.lastUpdated} · dernière revue {module.lastReviewed} · prochaine revue {module.nextReview} · {moduleResourceStats.resources} ressources dans le catalogue. Contenu pédagogique, non substitutif à un avis professionnel.</p>
    </main>
  </ClinicalShell>;
}

function FilterSelect({ label, value, onChange, options }: { label: string; value: string; onChange: (value: string) => void; options: string[] }) { return <label className="grid gap-1"><span className="text-[11px] font-bold uppercase tracking-wide text-[#65736f]">{label}</span><select aria-label={`Filtrer par ${label}`} value={value} onChange={event => onChange(event.target.value)} className="h-10 rounded-md border border-[#d3ddda] bg-white px-2 text-xs text-[#344844]"><option value={ALL}>Tous</option>{options.filter(item => item !== ALL).map(item => <option key={item} value={item}>{typeLabels[item as ModuleResourceType] ?? item}</option>)}</select></label>; }
