import { ClinicalShell } from "@/components/ClinicalShell";
import { Button } from "@/components/ui/button";
import { useAuth } from "@/_core/hooks/useAuth";
import { startLogin } from "@/const";
import { trpc } from "@/lib/trpc";
import { ArrowLeft, CheckCircle2, LockKeyhole, ShieldCheck } from "lucide-react";
import { Link } from "wouter";

const POLICY_VERSION = "analytics-v1.0";
export default function PrivacySettingsPage() {
  const { isAuthenticated, loading } = useAuth(); const utils = trpc.useUtils(); const consent = trpc.clinical.user.analyticsConsent.get.useQuery(undefined, { enabled: isAuthenticated }); const update = trpc.clinical.user.analyticsConsent.set.useMutation({ onSuccess: () => utils.clinical.user.analyticsConsent.get.invalidate() });
  if (loading) return <ClinicalShell><section className="container py-16 text-[#607771]">Chargement…</section></ClinicalShell>;
  if (!isAuthenticated) return <ClinicalShell><section className="container max-w-3xl py-14"><LockKeyhole className="h-8 w-8 text-[#2c8271]" /><h1 className="mt-4 font-serif text-4xl font-bold text-[#0d2b36]">Préférences de confidentialité</h1><p className="mt-4 leading-7 text-[#526b67]">Connectez-vous pour enregistrer vos préférences de mesure d’usage.</p><Button onClick={() => startLogin()} className="mt-6 bg-[#0d2b36]">Se connecter</Button></section></ClinicalShell>;
  const granted = consent.data?.status === "GRANTED";
  return <ClinicalShell><section className="container max-w-4xl py-12"><Link href="/fr/mon-espace" className="inline-flex items-center gap-2 text-sm font-bold text-[#1c7566]"><ArrowLeft className="h-4 w-4" />Mon espace</Link><p className="mt-7 text-xs font-bold uppercase tracking-[0.15em] text-[#39806f]">Préférences</p><h1 className="mt-3 font-serif text-4xl font-bold text-[#0d2b36]">Mesure d’usage et confidentialité</h1><p className="mt-4 max-w-3xl leading-7 text-[#526b67]">Votre choix n’affecte pas l’accès aux guides, au parcours, aux outils ou à votre espace de travail. Les analytics sont facultatives et réversibles.</p><div className="mt-8 grid gap-5 lg:grid-cols-[1fr_0.75fr]"><section className="rounded-2xl border border-[#dbe8e3] bg-white p-7 shadow-sm"><div className="flex items-center gap-3"><span className="flex h-10 w-10 items-center justify-center rounded-xl bg-[#e3f3ec] text-[#277e6e]"><ShieldCheck className="h-5 w-5" /></span><div><h2 className="font-bold text-[#1b4245]">Analytics non essentielles</h2><p className="text-sm text-[#607771]">Statut actuel : {granted ? "autorisées" : "refusées ou non définies"}</p></div></div><p className="mt-5 text-sm leading-6 text-[#526b67]">Si vous les autorisez, nous enregistrons uniquement des événements d’usage généraux après connexion : type d’événement, page consultée, contenu consulté et date. Nous n’enregistrons pas vos notes, vos cas, vos actions, une adresse IP, une empreinte navigateur ni une donnée de santé.</p><div className="mt-6 flex flex-wrap gap-3"><Button disabled={update.isPending || granted} onClick={() => update.mutate({ granted: true, policyVersion: POLICY_VERSION })} className="bg-[#0d2b36]"><CheckCircle2 className="mr-2 h-4 w-4" />Autoriser les analytics</Button><Button disabled={update.isPending || !granted} variant="outline" onClick={() => update.mutate({ granted: false, policyVersion: POLICY_VERSION })} className="border-[#cbded7]">Refuser ou retirer mon accord</Button></div>{update.isSuccess && <p className="mt-4 rounded-xl bg-[#eaf6ef] p-3 text-sm text-[#1d6a5d]">Votre préférence a été enregistrée.</p>}{update.error && <p className="mt-4 rounded-xl bg-rose-50 p-3 text-sm text-rose-800">{update.error.message}</p>}</section><aside className="rounded-2xl bg-[#0d2b36] p-6 text-white"><LockKeyhole className="h-5 w-5 text-[#a7dac7]" /><h2 className="mt-3 font-serif text-xl font-bold">Ce qui reste nécessaire</h2><p className="mt-3 text-sm leading-6 text-[#c9ded7]">Le service conserve le compte, son rôle et les dates de connexion nécessaires à l’authentification et à la sécurité du service. Ces éléments ne dépendent pas des analytics facultatives.</p><Link href="/fr/confidentialite" className="mt-5 inline-flex text-sm font-bold text-[#b8dfce]">Lire la politique de confidentialité</Link></aside></div></section></ClinicalShell>;
}
