import { ClinicalShell } from "@/components/ClinicalShell";
import { ContentStatusBadge } from "@/components/StatusBadge";
import { ResourceCard } from "@/components/ResourceCard";
import { Input } from "@/components/ui/input";
import { glossary, sources } from "@shared/clinicalContent";
import { moduleResources } from "@shared/moduleResources";
import { BookOpenCheck, ExternalLink, Search } from "lucide-react";
import { useMemo, useState } from "react";

export default function ResourcesPage() {
  const [query, setQuery] = useState("");
  const terms = useMemo(() => glossary.filter(entry => `${entry.term} ${entry.definition}`.toLowerCase().includes(query.toLowerCase())), [query]);
  const catalog = useMemo(() => moduleResources.filter(resource => `${resource.title} ${resource.description} ${resource.tags.join(" ")} ${resource.moduleIds.join(" ")}`.toLowerCase().includes(query.toLowerCase())), [query]);
  return <ClinicalShell>
    <section className="border-b border-[#d9e0de] bg-[#f1f3f2]"><div className="container py-10"><p className="text-xs font-bold uppercase tracking-[0.15em] text-[#536662]">Références & apprentissage</p><h1 className="mt-3 text-4xl font-bold tracking-tight text-[#142523]">Ressources et glossaire</h1><p className="mt-3 max-w-3xl leading-7 text-[#52625f]">Un catalogue transversal de guides, outils, checklists, modèles, formations et sources. Les contenus affichent leur statut et leur portée ; ils ne sont jamais automatiquement assimilés à une règle applicable.</p></div></section>
    <section className="container py-8"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-[0.14em] text-[#536662]">Catalogue transversal</p><h2 className="mt-2 text-2xl font-bold text-[#172c2d]">Trouver une ressource de travail</h2></div><span className="text-sm text-[#61716d]">{catalog.length} ressource{catalog.length > 1 ? "s" : ""}</span></div><div className="relative mt-4 max-w-2xl"><Search className="absolute left-3 top-3 h-4 w-4 text-[#71807d]" /><Input aria-label="Rechercher dans le catalogue de ressources" value={query} onChange={event => setQuery(event.target.value)} className="border-[#d3ddda] pl-9" placeholder="Estimand, protocole, source, checklist…" /></div><div className="mt-5 grid gap-4 md:grid-cols-2 xl:grid-cols-3">{catalog.map(resource => <ResourceCard key={resource.id} resource={resource} />)}</div>{catalog.length === 0 && <p className="mt-5 rounded-xl border border-dashed border-[#bbc8c4] bg-[#f5f7f6] p-5 text-sm text-[#596a66]">Ressources en cours de vérification ou aucun résultat.</p>}</section>
    <section className="container grid gap-8 pb-10 lg:grid-cols-[0.9fr_1.1fr]"><div><h2 className="text-2xl font-bold text-[#172c2d]">Sources initiales</h2><div className="mt-4 grid gap-3">{sources.map(source => <a key={source.id} href={source.url} target="_blank" rel="noreferrer" className="rounded-2xl border border-[#dce4e1] bg-white p-5 shadow-sm transition hover:border-[#7d918c] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[#314b47]"><div className="flex items-start justify-between gap-3"><BookOpenCheck className="h-5 w-5 shrink-0 text-[#394f4b]" /><ContentStatusBadge status={source.status} /></div><h3 className="mt-4 font-bold leading-6 text-[#1a302e]">{source.title}</h3><p className="mt-2 text-xs font-semibold uppercase tracking-wide text-[#5e6e6a]">{source.publisher} · {source.jurisdiction}</p><p className="mt-3 text-sm leading-6 text-[#61716d]">{source.scope}</p><span className="mt-4 inline-flex items-center gap-2 text-sm font-bold text-[#314b47]">Consulter la source <ExternalLink className="h-4 w-4" /></span></a>)}</div></div><div><div className="flex flex-wrap items-end justify-between gap-4"><div><h2 className="text-2xl font-bold text-[#172c2d]">Glossaire</h2><p className="mt-1 text-sm text-[#60716d]">Définitions pédagogiques et concises.</p></div><span className="text-sm text-[#60716d]">{terms.length} termes</span></div><dl className="mt-4 grid gap-3 sm:grid-cols-2">{terms.map(entry => <div key={entry.term} className="rounded-xl border border-[#dce4e1] bg-white p-4"><dt className="font-bold text-[#344d49]">{entry.term}</dt><dd className="mt-2 text-sm leading-6 text-[#59716d]">{entry.definition}</dd></div>)}</dl></div></section>
  </ClinicalShell>;
}
