import { ClinicalShell } from "@/components/ClinicalShell";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { ArrowLeft, Calculator, CalendarDays, CheckCircle2, FlaskConical, GitBranch, Info, Sigma, UsersRound } from "lucide-react";
import { useMemo, useState } from "react";
import { Link } from "wouter";

function invNorm(p:number){
 const a=[-39.6968302866538,220.946098424521,-275.928510446969,138.357751867269,-30.6647980661472,2.50662827745924];
 const b=[-54.4760987982241,161.585836858041,-155.698979859887,66.8013118877197,-13.2806815528857];
 const c=[-0.00778489400243029,-0.322396458041136,-2.40075827716184,-2.54973253934373,4.37466414146497,2.93816398269878];
 const d=[0.00778469570904146,0.32246712907004,2.445134137143,3.75440866190742];
 const pl=.02425,ph=1-pl; if(p<=0||p>=1)return NaN;
 if(p<pl){const q=Math.sqrt(-2*Math.log(p));const n=(((((c[0]*q+c[1])*q+c[2])*q+c[3])*q+c[4])*q)+c[5];const den=((((d[0]*q+d[1])*q+d[2])*q+d[3])*q)+1;return n/den;}
 if(p>ph){const q=Math.sqrt(-2*Math.log(1-p));const n=(((((c[0]*q+c[1])*q+c[2])*q+c[3])*q+c[4])*q)+c[5];const den=((((d[0]*q+d[1])*q+d[2])*q+d[3])*q)+1;return -(n/den);}
 const q=p-.5,r=q*q;const n=(((((a[0]*r+a[1])*r+a[2])*r+a[3])*r+a[4])*r+a[5])*q;const den=((((b[0]*r+b[1])*r+b[2])*r+b[3])*r+b[4])*r+1;return n/den;
}

const n2=(p1:number,p2:number,a:number,pow:number)=>{const za=invNorm(1-a/2),zb=invNorm(pow),pb=(p1+p2)/2;return Math.ceil(Math.pow(za*Math.sqrt(2*pb*(1-pb))+zb*Math.sqrt(p1*(1-p1)+p2*(1-p2)),2)/Math.pow(p2-p1,2))};
const cont=(delta:number,sd:number,a:number,pow:number)=>Math.ceil(2*Math.pow((invNorm(1-a/2)+invNorm(pow))*sd/delta,2));
const events=(hr:number,a:number,pow:number)=>Math.ceil(Math.pow(invNorm(1-a/2)+invNorm(pow),2)/Math.pow(Math.log(hr),2));
function Tool({title,icon,children}:{title:string;icon:React.ReactNode;children:React.ReactNode}){return <section className="rounded-2xl border border-[#dbe8e3] bg-white p-6 shadow-sm"><div className="flex items-center gap-2 text-[#2a8171]">{icon}<h2 className="font-serif text-xl font-bold text-[#173e43]">{title}</h2></div><div className="mt-5">{children}</div></section>}
function Field({label,children}:{label:string;children:React.ReactNode}){return <div className="grid gap-2"><Label className="font-semibold text-[#2d4d4e]">{label}</Label>{children}</div>}
export default function TrialToolsLab(){
 const [p1,setP1]=useState('0.30'),[p2,setP2]=useState('0.50'),[alpha,setAlpha]=useState('0.05'),[power,setPower]=useState('0.80');
 const [delta,setDelta]=useState('5'),[sd,setSd]=useState('10');
 const [hr,setHr]=useState('0.75');
 const [m,setM]=useState('20'),[icc,setIcc]=useState('0.05');
 const [clusters,setClusters]=useState('10'),[periods,setPeriods]=useState('5');
 const [monthly,setMonthly]=useState('5'),[centers,setCenters]=useState('8'),[target,setTarget]=useState('120');
 const [targetDay,setTargetDay]=useState('90'),[before,setBefore]=useState('14'),[after,setAfter]=useState('14');
 const bin=useMemo(()=>n2(Number(p1),Number(p2),Number(alpha),Number(power)),[p1,p2,alpha,power]);
 const con=useMemo(()=>cont(Number(delta),Number(sd),Number(alpha),Number(power)),[delta,sd,alpha,power]);
 const ev=useMemo(()=>events(Number(hr),Number(alpha),Number(power)),[hr,alpha,power]);
 const de=1+(Math.max(1,Number(m))-1)*Math.max(0,Number(icc)); const clusterN=Number.isFinite(bin)?Math.ceil(bin*de):0;
 const recruitment=Math.max(0,Number(monthly))*Math.max(0,Number(centers)); const months=recruitment>0?Math.ceil(Number(target)/recruitment):null;
 const stepp=Array.from({length:Math.max(1,Number(clusters)||1)},(_,i)=>Array.from({length:Math.max(2,Number(periods)||2)},(_,j)=>((i%(Math.max(1,Number(periods)||1-1)))<=j?'I':'C')));
 return <ClinicalShell><section className="border-b border-[#dce9e4] bg-[#edf5f1]"><div className="container py-10"><Link href="/fr/concevoir-un-essai" className="inline-flex items-center gap-2 text-sm font-bold text-[#1c7566]"><ArrowLeft className="h-4 w-4"/>Workspace</Link><p className="mt-6 text-xs font-bold uppercase tracking-[0.16em] text-[#39806f]">Clinical Trial Tools Lab</p><h1 className="mt-2 font-serif text-4xl font-bold text-[#0d2b36] sm:text-5xl">Laboratoire des outils de conception</h1><p className="mt-3 max-w-3xl text-lg leading-8 text-[#526b67]">Calculs de planification, calendrier, recrutement et design complexe. Les résultats indicatifs doivent être vérifiés par un biostatisticien lorsque le design ou les hypothèses sont spécifiques.</p></div></section><section className="container py-10"><div className="grid gap-5 xl:grid-cols-2"><Tool title="Effectif — endpoint binaire" icon={<Calculator/>}><div className="grid gap-4 sm:grid-cols-2"><Field label="Proportion contrôle"><Input value={p1} onChange={e=>setP1(e.target.value)}/></Field><Field label="Proportion intervention"><Input value={p2} onChange={e=>setP2(e.target.value)}/></Field><Field label="Alpha"><Input value={alpha} onChange={e=>setAlpha(e.target.value)}/></Field><Field label="Puissance"><Input value={power} onChange={e=>setPower(e.target.value)}/></Field></div><Result value={`${bin} participants / groupe`} note="Approximation normale bilatérale à deux groupes, sans allocation inégale ni correction spécifique."/></Tool>
 <Tool title="Effectif — endpoint continu" icon={<Sigma/>}><div className="grid gap-4 sm:grid-cols-2"><Field label="Différence attendue"><Input value={delta} onChange={e=>setDelta(e.target.value)}/></Field><Field label="Écart-type"><Input value={sd} onChange={e=>setSd(e.target.value)}/></Field><Field label="Alpha"><Input value={alpha} onChange={e=>setAlpha(e.target.value)}/></Field><Field label="Puissance"><Input value={power} onChange={e=>setPower(e.target.value)}/></Field></div><Result value={`${con} participants au total`} note="Approximation pour deux groupes de même taille."/></Tool>
 <Tool title="Time-to-event — nombre d’événements" icon={<FlaskConical/>}><div className="grid gap-4 sm:grid-cols-2"><Field label="Hazard ratio"><Input value={hr} onChange={e=>setHr(e.target.value)}/></Field><Field label="Alpha"><Input value={alpha} onChange={e=>setAlpha(e.target.value)}/></Field><Field label="Puissance"><Input value={power} onChange={e=>setPower(e.target.value)}/></Field></div><Result value={`${ev} événements requis`} note="Approximation de type Schoenfeld pour un HR et une allocation simple ; le nombre de participants dépend du taux d’événement et du suivi."/></Tool>
 <Tool title="Cluster randomized — design effect" icon={<UsersRound/>}><div className="grid gap-4 sm:grid-cols-2"><Field label="Participants / cluster"><Input value={m} onChange={e=>setM(e.target.value)}/></Field><Field label="ICC"><Input value={icc} onChange={e=>setIcc(e.target.value)}/></Field><Field label="Nombre de clusters"><Input value={clusters} onChange={e=>setClusters(e.target.value)}/></Field></div><Result value={`Design effect ${de.toFixed(2)} · effectif indicatif ${clusterN}`} note="Le nombre de clusters doit être planifié en fonction du modèle statistique, de la variation des tailles de clusters et des hypothèses de puissance."/></Tool>
 <Tool title="Stepped-wedge — planification des séquences" icon={<GitBranch/>}><div className="grid gap-4 sm:grid-cols-2"><Field label="Clusters"><Input value={clusters} onChange={e=>setClusters(e.target.value)}/></Field><Field label="Périodes"><Input value={periods} onChange={e=>setPeriods(e.target.value)}/></Field></div><div className="mt-4 overflow-auto rounded-xl border border-[#dbe8e3]"><table className="min-w-full text-xs"><tbody>{stepp.map((row,i)=><tr key={i}>{row.map((cell,j)=><td key={j} className={`border-b border-r border-[#e5eeeb] px-3 py-2 font-semibold ${cell==='I'?'bg-[#eaf7f1] text-[#176d60]':'bg-[#f7faf9] text-[#6a7f7b]'}`}>C{i+1} · P{j+1} · {cell}</td>)}</tr>)}</tbody></table></div><div className="mt-4 rounded-xl bg-[#fff8e8] p-4 text-sm text-[#735723]"><Info className="mr-2 inline h-4 w-4"/>Le stepped-wedge exige une méthode spécifique tenant compte des périodes et corrélations. Cette matrice est un outil de préparation, pas un calcul d’effectif validé.</div></Tool>
 <Tool title="Recrutement — scénario central" icon={<UsersRound/>}><div className="grid gap-4 sm:grid-cols-2"><Field label="Centres"><Input value={centers} onChange={e=>setCenters(e.target.value)}/></Field><Field label="Inclusions / centre / mois"><Input value={monthly} onChange={e=>setMonthly(e.target.value)}/></Field><Field label="Cible participants"><Input value={target} onChange={e=>setTarget(e.target.value)}/></Field></div><Result value={months?`${months} mois estimés`:"—"} note={`${recruitment} inclusions / mois dans le scénario saisi. Construire aussi des scénarios pessimiste et optimiste.`}/></Tool>
 <Tool title="Fenêtre de visite" icon={<CalendarDays/>}><div className="grid gap-4 sm:grid-cols-3"><Field label="Jour cible"><Input type="number" value={targetDay} onChange={e=>setTargetDay(e.target.value)}/></Field><Field label="Avant (j)"><Input type="number" value={before} onChange={e=>setBefore(e.target.value)}/></Field><Field label="Après (j)"><Input type="number" value={after} onChange={e=>setAfter(e.target.value)}/></Field></div><Result value={`J${Number(targetDay)-Number(before)} → J${Number(targetDay)+Number(after)}`} note="Fenêtre abstraite à mapper aux règles du protocole."/></Tool>
 </div><section className="mt-7 rounded-2xl border border-[#dbe8e3] bg-white p-6 shadow-sm"><h2 className="font-serif text-2xl font-bold text-[#153e43]">Méthodes avancées à valider</h2><div className="mt-5 grid gap-3 md:grid-cols-2 lg:grid-cols-3">{['Non-infériorité','Équivalence','Cross-over','Factoriel','Longitudinal / mixed models','Multiplicity / gatekeeping','Interim / alpha spending','Adaptive design / simulation','Missing data / sensitivity'].map(t=><div key={t} className="flex items-start gap-2 rounded-xl bg-[#f5f9f7] p-4 text-sm text-[#526c67]"><CheckCircle2 className="mt-0.5 h-4 w-4 shrink-0 text-[#2b8372]"/><div><strong>{t}</strong><p className="mt-1">Bibliothèque et aide méthodologique à utiliser avec validation spécialisée ; ne pas convertir une approximation en calcul confirmatoire.</p></div></div>)}</div></section></section></ClinicalShell>;
}
function Result({value,note}:{value:string;note:string}){return <div className="mt-5 rounded-xl bg-[#edf7f2] p-4"><p className="text-xl font-bold text-[#174b46]">{value}</p><p className="mt-1 text-xs leading-5 text-[#5b746e]">{note}</p></div>}
