import { and, desc, eq, inArray, sql } from "drizzle-orm";
import { drizzle } from "drizzle-orm/mysql2";
import { analyticsConsents, anonymousUsage, contentBacklog, contentItems, contentVersions, exportAuditLogs, feedback, favorites, InsertUser, jurisdictions, loginEvents, savedCaseItems, savedCases, sources, studyProjectCalculations, studyProjectMembers, studyProjectReferenceVersions, studyProjectReferences, studyProjectSections, studyProjectVersions, studyProjectVisits, studyProjects, users } from "../drizzle/schema";
import { ENV } from "./_core/env";

let _db: ReturnType<typeof drizzle> | null = null;

export async function getDb() {
  if (!_db && process.env.DATABASE_URL) {
    try { _db = drizzle(process.env.DATABASE_URL); } catch (error) { console.warn("[Database] Failed to connect:", error); _db = null; }
  }
  return _db;
}

export async function upsertUser(user: InsertUser): Promise<void> {
  if (!user.openId) throw new Error("User openId is required for upsert");
  const db = await getDb(); if (!db) return;
  const values: InsertUser = { openId: user.openId, lastSignedIn: user.lastSignedIn ?? new Date() };
  const updateSet: Record<string, unknown> = { lastSignedIn: values.lastSignedIn };
  for (const field of ["name", "email", "loginMethod"] as const) if (user[field] !== undefined) { values[field] = user[field] ?? null; updateSet[field] = user[field] ?? null; }
  values.role = user.role ?? (user.openId === ENV.ownerOpenId ? "admin" : "user"); updateSet.role = values.role;
  await db.insert(users).values(values).onDuplicateKeyUpdate({ set: updateSet });
  const persisted = await getUserByOpenId(user.openId);
  if (persisted) await db.insert(loginEvents).values({ userId: persisted.id, loginMethod: user.loginMethod ?? null });
}

export async function getUserByOpenId(openId: string) { const db = await getDb(); if (!db) return undefined; const result = await db.select().from(users).where(eq(users.openId, openId)).limit(1); return result[0]; }

export async function listFavoritesForUser(userId: number) { const db = await getDb(); if (!db) return []; return db.select().from(favorites).where(eq(favorites.userId, userId)).orderBy(desc(favorites.createdAt)); }
export async function toggleFavoriteForUser(userId: number, scenarioSlug: string) { const db = await getDb(); if (!db) return { saved: false, unavailable: true }; const existing = await db.select().from(favorites).where(and(eq(favorites.userId, userId), eq(favorites.scenarioSlug, scenarioSlug))).limit(1); if (existing[0]) { await db.delete(favorites).where(eq(favorites.id, existing[0].id)); return { saved: false, unavailable: false }; } await db.insert(favorites).values({ userId, scenarioSlug }); return { saved: true, unavailable: false }; }

export async function listSavedCasesForUser(userId: number) { const db = await getDb(); if (!db) return []; return db.select().from(savedCases).where(eq(savedCases.userId, userId)).orderBy(desc(savedCases.updatedAt)); }
export async function createSavedCaseForUser(input: { userId: number; title: string; scenarioSlug?: string; role?: string; phase?: string; jurisdiction?: string; note?: string }) { const db = await getDb(); if (!db) return { id: null, unavailable: true }; const result = await db.insert(savedCases).values({ ...input, dataSafetyConfirmed: true }); return { id: result[0].insertId, unavailable: false }; }
export async function getSavedCaseForUser(userId: number, id: number) { const db = await getDb(); if (!db) return undefined; const rows = await db.select().from(savedCases).where(and(eq(savedCases.id, id), eq(savedCases.userId, userId))).limit(1); if (!rows[0]) return undefined; const items = await db.select().from(savedCaseItems).where(eq(savedCaseItems.savedCaseId, id)).orderBy(savedCaseItems.itemOrder, savedCaseItems.createdAt); return { ...rows[0], items }; }
export async function updateSavedCaseForUser(userId: number, id: number, patch: { title?: string; note?: string | null; scenarioSlug?: string | null; role?: string | null; phase?: string | null; jurisdiction?: string | null }) { const db = await getDb(); if (!db) return false; const current = await getSavedCaseForUser(userId, id); if (!current) return false; await db.update(savedCases).set(patch).where(and(eq(savedCases.id, id), eq(savedCases.userId, userId))); return true; }
export async function deleteSavedCaseForUser(userId: number, id: number) { const db = await getDb(); if (!db) return false; const current = await getSavedCaseForUser(userId, id); if (!current) return false; await db.delete(savedCaseItems).where(eq(savedCaseItems.savedCaseId, id)); await db.delete(savedCases).where(and(eq(savedCases.id, id), eq(savedCases.userId, userId))); return true; }
export async function createSavedCaseItemForUser(userId: number, input: { savedCaseId: number; itemType: "ACTION" | "CHECKLIST" | "MILESTONE"; title: string; dueAt?: Date | null }) { const db = await getDb(); if (!db) return { id: null, unavailable: true }; const parent = await getSavedCaseForUser(userId, input.savedCaseId); if (!parent) return { id: null, unavailable: false, forbidden: true }; const result = await db.insert(savedCaseItems).values({ ...input, itemOrder: parent.items.length }); return { id: result[0].insertId, unavailable: false, forbidden: false }; }
export async function updateSavedCaseItemForUser(userId: number, id: number, patch: { title?: string; completed?: boolean; dueAt?: Date | null }) { const db = await getDb(); if (!db) return false; const rows = await db.select({ id: savedCaseItems.id }).from(savedCaseItems).innerJoin(savedCases, eq(savedCaseItems.savedCaseId, savedCases.id)).where(and(eq(savedCaseItems.id, id), eq(savedCases.userId, userId))).limit(1); if (!rows[0]) return false; await db.update(savedCaseItems).set(patch).where(eq(savedCaseItems.id, id)); return true; }
export async function deleteSavedCaseItemForUser(userId: number, id: number) { const db = await getDb(); if (!db) return false; const rows = await db.select({ id: savedCaseItems.id }).from(savedCaseItems).innerJoin(savedCases, eq(savedCaseItems.savedCaseId, savedCases.id)).where(and(eq(savedCaseItems.id, id), eq(savedCases.userId, userId))).limit(1); if (!rows[0]) return false; await db.delete(savedCaseItems).where(eq(savedCaseItems.id, id)); return true; }

export type ContentItemInput = { slug: string; contentType: "SCENARIO" | "GUIDE" | "MODULE" | "SOURCE_NOTE"; title: string; summary: string; body?: string | null; jurisdiction: string; versionLabel: string; status: "VERIFIED" | "NEEDS_REVIEW" | "OUTDATED" | "DRAFT" | "ARCHIVED"; reviewAt?: Date | null };
export async function listPublicContentItems() { const db = await getDb(); if (!db) return []; return db.select().from(contentItems).where(eq(contentItems.status, "VERIFIED")).orderBy(desc(contentItems.publishedAt), desc(contentItems.updatedAt)); }
export async function listAdminContentItems() { const db = await getDb(); if (!db) return []; return db.select().from(contentItems).orderBy(desc(contentItems.updatedAt)); }
export async function createContentItem(authorId: number, input: ContentItemInput) { const db = await getDb(); if (!db) return { id: null, unavailable: true }; const publishedAt = input.status === "VERIFIED" ? new Date() : null; const result = await db.insert(contentItems).values({ ...input, publishedAt, createdByUserId: authorId, updatedByUserId: authorId }); const id = Number(result[0].insertId); await db.insert(contentVersions).values({ entityType: "contentItem", entityId: id, versionLabel: input.versionLabel, changeReason: "Création", authorLabel: `admin:${authorId}`, snapshot: { ...input, publishedAt: publishedAt?.toISOString() } }); return { id, unavailable: false }; }
export async function updateContentItem(authorId: number, id: number, input: ContentItemInput, reason: string) { const db = await getDb(); if (!db) return false; const current = await db.select().from(contentItems).where(eq(contentItems.id, id)).limit(1); if (!current[0]) return false; const publishedAt = input.status === "VERIFIED" ? current[0].publishedAt ?? new Date() : input.status === "ARCHIVED" ? current[0].publishedAt : current[0].publishedAt; await db.update(contentItems).set({ ...input, publishedAt, updatedByUserId: authorId }).where(eq(contentItems.id, id)); await db.insert(contentVersions).values({ entityType: "contentItem", entityId: id, versionLabel: input.versionLabel, changeReason: reason || "Révision", authorLabel: `admin:${authorId}`, snapshot: { ...input, publishedAt: publishedAt?.toISOString() } }); return true; }
export async function archiveContentItem(authorId: number, id: number, reason: string) { const db = await getDb(); if (!db) return false; const current = await db.select().from(contentItems).where(eq(contentItems.id, id)).limit(1); if (!current[0]) return false; await db.update(contentItems).set({ status: "ARCHIVED", updatedByUserId: authorId }).where(eq(contentItems.id, id)); await db.insert(contentVersions).values({ entityType: "contentItem", entityId: id, versionLabel: current[0].versionLabel, changeReason: reason || "Archivage", authorLabel: `admin:${authorId}`, snapshot: { ...current[0], status: "ARCHIVED" } }); return true; }
export async function listContentVersions(itemId: number) { const db = await getDb(); if (!db) return []; return db.select().from(contentVersions).where(and(eq(contentVersions.entityType, "contentItem"), eq(contentVersions.entityId, itemId))).orderBy(desc(contentVersions.createdAt)); }

export type SourceRecordInput = { externalId: string; title: string; publisher: string; sourceUrl: string; jurisdiction: string; versionLabel?: string | null; scope?: string | null; status: "VERIFIED" | "NEEDS_REVIEW" | "OUTDATED" | "DRAFT" | "ARCHIVED"; isOfficial: boolean; nextReviewAt?: Date | null };
export type JurisdictionRecordInput = { slug: string; name: string; scope?: string | null; status: "VERIFIED" | "NEEDS_REVIEW" | "OUTDATED" | "DRAFT" | "ARCHIVED"; nextReviewAt?: Date | null };
export async function listAdminSources() { const db = await getDb(); if (!db) return []; return db.select().from(sources).orderBy(desc(sources.updatedAt)); }
export async function listAdminJurisdictions() { const db = await getDb(); if (!db) return []; return db.select().from(jurisdictions).orderBy(jurisdictions.name); }
export async function createSourceRecord(authorId: number, input: SourceRecordInput) { const db = await getDb(); if (!db) return { id: null, unavailable: true }; const result = await db.insert(sources).values({ ...input, verifiedAt: input.status === "VERIFIED" ? new Date() : null }); const id = Number(result[0].insertId); await db.insert(contentVersions).values({ entityType: "source", entityId: id, versionLabel: input.versionLabel ?? "v1.0", changeReason: "Création de source", authorLabel: `admin:${authorId}`, snapshot: input }); return { id, unavailable: false }; }
export async function updateSourceRecord(authorId: number, id: number, input: SourceRecordInput, reason: string) { const db = await getDb(); if (!db) return false; const current = await db.select().from(sources).where(eq(sources.id, id)).limit(1); if (!current[0]) return false; await db.update(sources).set({ ...input, verifiedAt: input.status === "VERIFIED" ? new Date() : current[0].verifiedAt }).where(eq(sources.id, id)); await db.insert(contentVersions).values({ entityType: "source", entityId: id, versionLabel: input.versionLabel ?? current[0].versionLabel ?? "v1.0", changeReason: reason || "Révision de source", authorLabel: `admin:${authorId}`, snapshot: input }); return true; }
export async function createJurisdictionRecord(authorId: number, input: JurisdictionRecordInput) { const db = await getDb(); if (!db) return { id: null, unavailable: true }; const result = await db.insert(jurisdictions).values({ ...input, lastVerifiedAt: input.status === "VERIFIED" ? new Date() : null }); const id = Number(result[0].insertId); await db.insert(contentVersions).values({ entityType: "jurisdiction", entityId: id, versionLabel: "v1.0", changeReason: "Création de juridiction", authorLabel: `admin:${authorId}`, snapshot: input }); return { id, unavailable: false }; }
export async function updateJurisdictionRecord(authorId: number, id: number, input: JurisdictionRecordInput, reason: string) { const db = await getDb(); if (!db) return false; const current = await db.select().from(jurisdictions).where(eq(jurisdictions.id, id)).limit(1); if (!current[0]) return false; await db.update(jurisdictions).set({ ...input, lastVerifiedAt: input.status === "VERIFIED" ? new Date() : current[0].lastVerifiedAt }).where(eq(jurisdictions.id, id)); await db.insert(contentVersions).values({ entityType: "jurisdiction", entityId: id, versionLabel: "v1.0", changeReason: reason || "Révision de juridiction", authorLabel: `admin:${authorId}`, snapshot: input }); return true; }

export async function recordFeedback(input: { helpful: boolean; comment?: string; scenarioSlug?: string }) { const db = await getDb(); if (!db) return { stored: false }; await db.insert(feedback).values(input); return { stored: true }; }
export async function createContentBacklog(input: { role?: string; studyType?: string; phase?: string; jurisdiction?: string; requestSummary: string }) { const db = await getDb(); if (!db) return { stored: false }; const result = await db.insert(contentBacklog).values(input); return { stored: true, id: result[0].insertId }; }
export async function recordAnonymousUsage(input: { eventName: string; route?: string; contentSlug?: string; properties?: Record<string, string | number | boolean> }) { const db = await getDb(); if (!db) return { stored: false }; await db.insert(anonymousUsage).values(input); return { stored: true }; }
export async function listRecentFeedback() { const db = await getDb(); if (!db) return []; return db.select().from(feedback).orderBy(desc(feedback.createdAt)).limit(20); }
export async function listContentBacklog() { const db = await getDb(); if (!db) return []; return db.select().from(contentBacklog).orderBy(desc(contentBacklog.createdAt)).limit(20); }
export async function listUsageAggregates() { const db = await getDb(); if (!db) return []; return db.select({ eventName: anonymousUsage.eventName, count: sql<number>`count(*)` }).from(anonymousUsage).groupBy(anonymousUsage.eventName); }
export async function getAnalyticsConsent(userId: number) { const db = await getDb(); if (!db) return undefined; const result = await db.select().from(analyticsConsents).where(eq(analyticsConsents.userId, userId)).limit(1); return result[0]; }
export async function setAnalyticsConsent(userId: number, granted: boolean, policyVersion: string) { const db = await getDb(); if (!db) return { stored: false }; const now = new Date(); await db.insert(analyticsConsents).values({ userId, status: granted ? "GRANTED" : "DENIED", policyVersion, grantedAt: granted ? now : null, revokedAt: granted ? null : now }).onDuplicateKeyUpdate({ set: { status: granted ? "GRANTED" : "DENIED", policyVersion, grantedAt: granted ? now : null, revokedAt: granted ? null : now } }); return { stored: true, granted }; }
export async function getAdminAnalyticsExport() { const db = await getDb(); if (!db) return { users: [], usage: [], exports: [] }; const [userRows, consentRows, loginRows, favoriteRows, caseRows, usageRows, exportRows] = await Promise.all([db.select().from(users), db.select().from(analyticsConsents), db.select().from(loginEvents), db.select().from(favorites), db.select().from(savedCases), listUsageAggregates(), db.select().from(exportAuditLogs).orderBy(desc(exportAuditLogs.createdAt)).limit(100)]); const consentByUser = new Map(consentRows.map(item => [item.userId, item])); const loginByUser = new Map<number, number>(); const favoriteByUser = new Map<number, number>(); const caseByUser = new Map<number, number>(); loginRows.forEach(item => loginByUser.set(item.userId, (loginByUser.get(item.userId) ?? 0) + 1)); favoriteRows.forEach(item => favoriteByUser.set(item.userId, (favoriteByUser.get(item.userId) ?? 0) + 1)); caseRows.forEach(item => caseByUser.set(item.userId, (caseByUser.get(item.userId) ?? 0) + 1)); return { users: userRows.map(item => ({ id: item.id, name: item.name, email: item.email, role: item.role, createdAt: item.createdAt, lastSignedIn: item.lastSignedIn, loginCount: loginByUser.get(item.id) ?? 0, consent: consentByUser.get(item.id)?.status ?? "NON_DEFINI", consentUpdatedAt: consentByUser.get(item.id)?.updatedAt ?? null, favoritesCount: favoriteByUser.get(item.id) ?? 0, genericCasesCount: caseByUser.get(item.id) ?? 0 })), usage: usageRows, exports: exportRows }; }
export async function recordExportAudit(requestedByUserId: number, exportType: string, destination: string | null, rowCount: number) { const db = await getDb(); if (!db) return { stored: false }; await db.insert(exportAuditLogs).values({ requestedByUserId, exportType, destination, rowCount }); return { stored: true }; }

export type StudyProjectInput = { studyId: string; acronym?: string; title: string; shortTitle?: string; studyQuestion?: string; indication?: string; condition?: string; sponsor?: string; coordinatingCenter?: string; principalInvestigator?: string; studyType?: string; interventionType?: string; phase?: string; jurisdiction: string; status: "DRAFT" | "IN_REVIEW" | "READY_FOR_REVIEW" | "ARCHIVED"; protocolVersion: string };
export async function listStudyProjects(userId: number) { const db = await getDb(); if (!db) return []; const memberships = await db.select({ studyProjectId: studyProjectMembers.studyProjectId }).from(studyProjectMembers).where(eq(studyProjectMembers.userId, userId)); const sharedIds = memberships.map(item => item.studyProjectId); if (!sharedIds.length) return db.select().from(studyProjects).where(eq(studyProjects.userId, userId)).orderBy(desc(studyProjects.updatedAt)); return db.select().from(studyProjects).where(inArray(studyProjects.id, sharedIds)).orderBy(desc(studyProjects.updatedAt)); }
export async function getStudyProjectAccess(userId: number, studyProjectId: number) { const db = await getDb(); if (!db) return undefined; const project = await db.select().from(studyProjects).where(eq(studyProjects.id, studyProjectId)).limit(1); if (!project[0]) return undefined; if (project[0].userId === userId) return "OWNER" as const; const member = await db.select().from(studyProjectMembers).where(and(eq(studyProjectMembers.studyProjectId, studyProjectId), eq(studyProjectMembers.userId, userId))).limit(1); return member[0]?.projectRole; }
export async function getStudyProject(userId: number, id: number) { const db = await getDb(); if (!db) return undefined; const access = await getStudyProjectAccess(userId, id); if (!access) return undefined; const rows = await db.select().from(studyProjects).where(eq(studyProjects.id, id)).limit(1); if (!rows[0]) return undefined; const [sections, versions, calculations, members, visits, references] = await Promise.all([db.select().from(studyProjectSections).where(eq(studyProjectSections.studyProjectId, id)).orderBy(studyProjectSections.updatedAt), db.select().from(studyProjectVersions).where(eq(studyProjectVersions.studyProjectId, id)).orderBy(desc(studyProjectVersions.createdAt)).limit(50), db.select().from(studyProjectCalculations).where(eq(studyProjectCalculations.studyProjectId, id)).orderBy(desc(studyProjectCalculations.createdAt)).limit(50), db.select().from(studyProjectMembers).where(eq(studyProjectMembers.studyProjectId, id)), db.select().from(studyProjectVisits).where(eq(studyProjectVisits.studyProjectId, id)).orderBy(studyProjectVisits.visitOrder), db.select().from(studyProjectReferences).where(eq(studyProjectReferences.studyProjectId, id)).orderBy(desc(studyProjectReferences.updatedAt))]); return { ...rows[0], access, sections, versions, calculations, members, visits, references }; }
export async function createStudyProject(userId: number, input: StudyProjectInput) { const db = await getDb(); if (!db) return { id: null, unavailable: true }; const result = await db.insert(studyProjects).values({ userId, ...input, dataSafetyConfirmed: true }); const id = Number(result[0].insertId); await db.insert(studyProjectMembers).values({ studyProjectId: id, userId, projectRole: "OWNER" }); await db.insert(studyProjectVersions).values({ studyProjectId: id, versionLabel: input.protocolVersion, changeReason: "Création du projet", snapshot: input, createdByUserId: userId }); return { id, unavailable: false }; }
export async function updateStudyProject(userId: number, id: number, input: StudyProjectInput, changeReason: string) { const db = await getDb(); if (!db) return false; const current = await getStudyProject(userId, id); if (!current || current.access !== "OWNER") return false; await db.update(studyProjects).set(input).where(and(eq(studyProjects.id, id), eq(studyProjects.userId, userId))); const snapshot = { project: input, sections: current.sections.map(section => ({ sectionKey: section.sectionKey, payload: section.payload, versionNumber: section.versionNumber })) }; await db.insert(studyProjectVersions).values({ studyProjectId: id, versionLabel: input.protocolVersion, changeReason, snapshot, createdByUserId: userId }); return true; }
export async function saveStudySection(userId: number, input: { studyProjectId: number; sectionKey: string; title: string; payload: Record<string, unknown>; completionState: "NOT_STARTED" | "IN_PROGRESS" | "COMPLETE" | "NEEDS_REVIEW" }) { const db = await getDb(); if (!db) return false; const project = await getStudyProject(userId, input.studyProjectId); if (!project || (project.access !== "OWNER" && project.access !== "EDITOR")) return false; const existing = project.sections.find(section => section.sectionKey === input.sectionKey); if (existing) { const versionNumber = existing.versionNumber + 1; await db.update(studyProjectSections).set({ title: input.title, payload: input.payload, completionState: input.completionState, versionNumber, updatedByUserId: userId }).where(eq(studyProjectSections.id, existing.id)); await db.insert(studyProjectVersions).values({ studyProjectId: input.studyProjectId, versionLabel: project.protocolVersion, changeReason: `Mise à jour : ${input.title}`, snapshot: { sectionKey: input.sectionKey, payload: input.payload, versionNumber }, createdByUserId: userId }); return { id: existing.id, versionNumber }; }
  const result = await db.insert(studyProjectSections).values({ ...input, updatedByUserId: userId }); const id = Number(result[0].insertId); await db.insert(studyProjectVersions).values({ studyProjectId: input.studyProjectId, versionLabel: project.protocolVersion, changeReason: `Création : ${input.title}`, snapshot: { sectionKey: input.sectionKey, payload: input.payload, versionNumber: 1 }, createdByUserId: userId }); return { id, versionNumber: 1 }; }
export async function saveStudyCalculation(userId: number, studyProjectId: number, calculationType: string, assumptions: Record<string, unknown>, result: Record<string, unknown>, warning: string) { const db = await getDb(); if (!db) return { id: null, unavailable: true }; const project = await getStudyProject(userId, studyProjectId); if (!project || (project.access !== "OWNER" && project.access !== "EDITOR")) return { id: null, unavailable: false, forbidden: true }; const inserted = await db.insert(studyProjectCalculations).values({ studyProjectId, calculationType, assumptions, result, warning, createdByUserId: userId }); return { id: Number(inserted[0].insertId), unavailable: false, forbidden: false }; }
export async function addStudyProjectMember(ownerId: number, studyProjectId: number, userId: number, projectRole: "EDITOR" | "REVIEWER" | "VIEWER") { const db = await getDb(); if (!db) return false; const access = await getStudyProjectAccess(ownerId, studyProjectId); if (access !== "OWNER") return false; await db.insert(studyProjectMembers).values({ studyProjectId, userId, projectRole }).onDuplicateKeyUpdate({ set: { projectRole } }); return true; }
export async function saveStudyVisit(userId: number, input: { studyProjectId: number; id?: number; label: string; visitOrder: number; targetDay: number; windowBeforeDays: number; windowAfterDays: number; assessments: string[]; participantStage?: string | null }) { const db = await getDb(); if (!db) return false; const access = await getStudyProjectAccess(userId, input.studyProjectId); if (access !== "OWNER" && access !== "EDITOR") return false; const { id, ...payload } = input; if (id) { await db.update(studyProjectVisits).set(payload).where(eq(studyProjectVisits.id, id)); return { id }; } const result = await db.insert(studyProjectVisits).values(payload); return { id: Number(result[0].insertId) }; }
export async function deleteStudyVisit(userId: number, studyProjectId: number, id: number) { const db = await getDb(); if (!db) return false; const access = await getStudyProjectAccess(userId, studyProjectId); if (access !== "OWNER" && access !== "EDITOR") return false; await db.delete(studyProjectVisits).where(and(eq(studyProjectVisits.id, id), eq(studyProjectVisits.studyProjectId, studyProjectId))); return true; }
export async function saveStudyReference(userId: number, input: { studyProjectId: number; sectionKey: string; citation: string; sourceUrl?: string | null; referenceStatus: "VERIFIED" | "NEEDS_REVIEW" | "OUTDATED" | "DRAFT" | "ARCHIVED"; versionLabel: string; reviewedAt?: Date | null; changeReason?: string }) { const db = await getDb(); if (!db) return { id: null, unavailable: true }; const access = await getStudyProjectAccess(userId, input.studyProjectId); if (access !== "OWNER" && access !== "EDITOR") return { id: null, forbidden: true }; const result = await db.insert(studyProjectReferences).values({ ...input, reviewedAt: input.reviewedAt ?? null, createdByUserId: userId }); const id = Number(result[0].insertId); await db.insert(studyProjectReferenceVersions).values({ studyProjectReferenceId: id, versionNumber: 1, versionLabel: input.versionLabel, changeReason: input.changeReason ?? "Création de la référence", snapshot: { citation: input.citation, sourceUrl: input.sourceUrl ?? null, referenceStatus: input.referenceStatus, reviewedAt: input.reviewedAt?.toISOString() ?? null }, reviewedAt: input.reviewedAt ?? null, createdByUserId: userId }); return { id, forbidden: false }; }
export async function updateStudyReference(userId: number, input: { studyProjectId: number; id: number; citation: string; sourceUrl?: string | null; referenceStatus: "VERIFIED" | "NEEDS_REVIEW" | "OUTDATED" | "DRAFT" | "ARCHIVED"; versionLabel: string; reviewedAt?: Date | null; changeReason: string }) { const db = await getDb(); if (!db) return { id: null, unavailable: true }; const access = await getStudyProjectAccess(userId, input.studyProjectId); if (access !== "OWNER" && access !== "EDITOR") return { id: null, forbidden: true }; const existing = await db.select().from(studyProjectReferences).where(and(eq(studyProjectReferences.id, input.id), eq(studyProjectReferences.studyProjectId, input.studyProjectId))).limit(1); if (!existing[0]) return { id: null, forbidden: true }; const versionNumber = existing[0].versionNumber + 1; await db.update(studyProjectReferences).set({ citation: input.citation, sourceUrl: input.sourceUrl ?? null, referenceStatus: input.referenceStatus, versionLabel: input.versionLabel, versionNumber, reviewedAt: input.reviewedAt ?? null }).where(and(eq(studyProjectReferences.id, input.id), eq(studyProjectReferences.studyProjectId, input.studyProjectId))); await db.insert(studyProjectReferenceVersions).values({ studyProjectReferenceId: input.id, versionNumber, versionLabel: input.versionLabel, changeReason: input.changeReason, snapshot: { citation: input.citation, sourceUrl: input.sourceUrl ?? null, referenceStatus: input.referenceStatus, reviewedAt: input.reviewedAt?.toISOString() ?? null }, reviewedAt: input.reviewedAt ?? null, createdByUserId: userId }); return { id: input.id, forbidden: false }; }
export async function listStudyReferenceVersions(userId: number, studyProjectId: number, referenceId: number) { const db = await getDb(); if (!db) return []; const access = await getStudyProjectAccess(userId, studyProjectId); if (!access) return []; return db.select().from(studyProjectReferenceVersions).where(eq(studyProjectReferenceVersions.studyProjectReferenceId, referenceId)).orderBy(desc(studyProjectReferenceVersions.versionNumber)); }
