export const designSteps = [
  { key: "question", title: "Question" }, { key: "population", title: "Population" }, { key: "intervention", title: "Intervention" }, { key: "comparator", title: "Comparateur" }, { key: "outcome", title: "Outcome" }, { key: "estimand", title: "Estimand" }, { key: "design", title: "Design" }, { key: "randomisation", title: "Randomisation" }, { key: "sample_size", title: "Effectif" }, { key: "schedule", title: "Calendrier" }, { key: "statistics", title: "Statistiques" }, { key: "risks", title: "Risques" }, { key: "feasibility", title: "Faisabilité" }, { key: "protocol", title: "Protocole" }, { key: "regulatory", title: "Réglementaire" }, { key: "reporting", title: "Reporting" }, { key: "final_review", title: "Vérification finale" },
] as const;

export type StudySectionPayload = Record<string, unknown>;
export type CoherenceIssue = { level: "INCOMPATIBLE" | "INCOMPLET" | "ATTENTION"; section: string; message: string; recommendation: string };

export function evaluateDesignCoherence(sections: Array<{ sectionKey: string; payload: unknown }>) {
  const byKey = new Map(sections.map(item => [item.sectionKey, item.payload && typeof item.payload === "object" ? item.payload as StudySectionPayload : {}])); const issues: CoherenceIssue[] = [];
  const question = byKey.get("question") ?? {}; const objectives = Array.isArray((byKey.get("outcome") ?? {}).objectives) ? ((byKey.get("outcome") ?? {}).objectives as Array<Record<string, unknown>>) : []; const endpoints = Array.isArray((byKey.get("outcome") ?? {}).endpoints) ? ((byKey.get("outcome") ?? {}).endpoints as Array<Record<string, unknown>>) : []; const primaryEndpoint = endpoints.find(endpoint => endpoint.priority === "PRIMARY") ?? endpoints[0];
  if (!question.population || !question.intervention || !question.outcome) issues.push({ level: "INCOMPLET", section: "Question", message: "La question PICO/PICOT ne contient pas encore toutes les composantes Population, Intervention et Outcome.", recommendation: "Compléter la question avant de figer les objectifs et l’effectif." });
  if (!objectives.length) issues.push({ level: "INCOMPLET", section: "Objectifs", message: "Aucun objectif n’est défini.", recommendation: "Définir au minimum un objectif principal avec population, endpoint et temps." });
  if (!endpoints.length) issues.push({ level: "INCOMPLET", section: "Endpoints", message: "Aucun endpoint n’est défini.", recommendation: "Associer un endpoint mesurable à chaque objectif principal." });
  const primaryEndpoints = endpoints.filter(endpoint => endpoint.priority === "PRIMARY"); if (primaryEndpoints.length > 1) issues.push({ level: "ATTENTION", section: "Endpoints", message: "Plusieurs endpoints sont marqués comme primaires.", recommendation: "Documenter une stratégie de multiplicité ou hiérarchiser les endpoints." }); if (endpoints.length && !primaryEndpoints.length) issues.push({ level: "ATTENTION", section: "Endpoints", message: "Aucun endpoint primaire n’est identifié.", recommendation: "Définir la priorité de chaque endpoint." });
  const estimand = byKey.get("estimand") ?? {}; if (endpoints.length && (!estimand.population || !estimand.variable || !estimand.strategy)) issues.push({ level: "INCOMPLET", section: "Estimand", message: "L’estimand n’est pas suffisamment documenté pour l’endpoint principal.", recommendation: "Documenter population, traitement, variable, événements intercurrents et stratégie." });
  const design = byKey.get("design") ?? {}; const randomisation = byKey.get("randomisation") ?? {}; const blinding = byKey.get("blinding") ?? {}; const sample = byKey.get("sample_size") ?? {}; if (!design.selectedDesign) issues.push({ level: "INCOMPLET", section: "Design", message: "Aucun design d’étude n’est sélectionné.", recommendation: "Comparer les designs et documenter les hypothèses retenues." });
  const randomisedDesign = /random|cluster|stepped/i.test(String(design.selectedDesign ?? "")); if (randomisedDesign && !String(randomisation.method ?? "").trim()) issues.push({ level: "INCOMPLET", section: "Randomisation", message: "Le design sélectionné requiert une méthode de randomisation documentée.", recommendation: "Préciser méthode théorique, ratio, stratification et système validé prévu pour l’allocation réelle." });
  if (randomisedDesign && !String(randomisation.allocation ?? "").trim()) issues.push({ level: "INCOMPLET", section: "Randomisation", message: "Le ratio d’allocation n’est pas renseigné.", recommendation: "Documenter le ratio, les hypothèses de blocs/strates et l’impact sur l’effectif." });
  if (randomisedDesign && !String(blinding.allocationConcealment ?? randomisation.allocationConcealment ?? "").trim()) issues.push({ level: "INCOMPLET", section: "Dissimulation d’allocation", message: "La dissimulation de l’allocation n’est pas décrite.", recommendation: "Décrire un mécanisme prévu dans un système validé ; cette plateforme ne remplace pas un IRT/IWRS." });
  if (String(blinding.blinding ?? "").trim() && !String(blinding.unblinding ?? "").trim()) issues.push({ level: "ATTENTION", section: "Aveugle", message: "Un niveau d’aveugle est indiqué sans procédure de levée d’aveugle documentée.", recommendation: "Documenter les personnes autorisées, la justification, la traçabilité et le circuit d’urgence applicable." });
  const statistics = byKey.get("statistics") ?? {}; if (endpoints.length && !String(statistics.primaryAnalysis ?? "").trim()) issues.push({ level: "INCOMPLET", section: "Statistiques", message: "L’analyse principale n’est pas documentée pour l’endpoint principal.", recommendation: "Préciser modèle, population d’analyse, covariables, données manquantes et analyses de sensibilité." });
  const endpointVariable = String(primaryEndpoint?.variable ?? primaryEndpoint?.name ?? "").trim().toLowerCase(); const estimandVariable = String(estimand.variable ?? "").trim().toLowerCase(); const analysisVariable = String(statistics.endpointVariable ?? statistics.variable ?? "").trim().toLowerCase(); const endpointScale = String(primaryEndpoint?.scale ?? primaryEndpoint?.dataType ?? "").toUpperCase(); const calculationType = String(sample.calculationType ?? "").toUpperCase();
  if (endpointVariable && estimandVariable && endpointVariable !== estimandVariable) issues.push({ level: "INCOMPATIBLE", section: "Chaînage méthodologique", message: "La variable de l’estimand ne correspond pas à l’endpoint principal.", recommendation: "Employer la même variable ou documenter explicitement une transformation validée." });
  if (endpointVariable && analysisVariable && endpointVariable !== analysisVariable) issues.push({ level: "INCOMPATIBLE", section: "Chaînage méthodologique", message: "La variable de l’analyse principale ne correspond pas à l’endpoint principal.", recommendation: "Aligner endpoint, modèle d’analyse et population d’analyse." });
  if (endpointScale === "BINARY" && calculationType && calculationType !== "BINARY") issues.push({ level: "INCOMPATIBLE", section: "Chaînage méthodologique", message: "Le type de calcul d’effectif ne correspond pas à un endpoint binaire.", recommendation: "Utiliser un calcul binaire ou justifier une méthode spécifique validée." });
  if ((endpointScale === "CONTINUOUS" || endpointScale === "CONTINU") && calculationType && calculationType !== "CONTINUOUS") issues.push({ level: "INCOMPATIBLE", section: "Chaînage méthodologique", message: "Le type de calcul d’effectif ne correspond pas à un endpoint continu.", recommendation: "Utiliser un calcul continu ou justifier une méthode spécifique validée." });
  if (!String(sample.analysisPopulation ?? "").trim()) issues.push({ level: "INCOMPLET", section: "Effectif", message: "La population d’analyse associée à l’effectif n’est pas documentée.", recommendation: "Préciser la population et l’aligner à l’estimand et à l’analyse principale." });
  if (!sample.calculationType || !sample.assumptionsReviewed) issues.push({ level: "INCOMPLET", section: "Effectif", message: "Les hypothèses de calcul d’effectif ne sont pas confirmées.", recommendation: "Revoir alpha, puissance, effet attendu, attrition et population d’analyse avec un biostatisticien." });
  const status = issues.some(item => item.level === "INCOMPATIBLE") ? "Incompatible" : issues.some(item => item.level === "INCOMPLET") ? "Incomplet" : issues.some(item => item.level === "ATTENTION") ? "Attention" : "Cohérent";
  return { status, issues, checkedSteps: designSteps.length, completedSections: sections.length };
}

export function evaluateTrialAudit(sections: Array<{ sectionKey: string; payload: unknown }>) { const coherence = evaluateDesignCoherence(sections); const byKey = new Map(sections.map(item => [item.sectionKey, item.payload && typeof item.payload === "object" ? item.payload as StudySectionPayload : {}])); const has = (key: string, field?: string) => { const value = byKey.get(key); return field ? Boolean(String(value?.[field] ?? "").trim()) : Boolean(value && Object.keys(value).length); }; const auditIssues: CoherenceIssue[] = []; const add = (condition: boolean, section: string, message: string, recommendation: string) => { if (condition) auditIssues.push({ level: "INCOMPLET", section, message, recommendation }); };
  add(!(has("protocol", "synopsis") && has("sap", "analysisSets") && has("statistics", "primaryAnalysis")), "Protocole ↔ SAP", "Le synopsis de protocole, les jeux d’analyse et l’analyse principale ne sont pas tous documentés.", "Relier les objectifs et endpoints du protocole aux populations d’analyse, modèles, données manquantes et analyses de sensibilité du SAP.");
  add(!(has("schedule", "visits") && has("schedule", "assessments")), "Calendrier ↔ évaluations", "Les visites et les évaluations associées ne sont pas toutes structurées.", "Documenter le calendrier, les fenêtres et le lien entre procédure, endpoint, sécurité, intervention et laboratoire.");
  add(!(has("recruitment", "fpiLpiPlan") && has("feasibility") && has("schedule", "followUp")), "Recrutement ↔ calendrier", "Les jalons de recrutement, la faisabilité et le suivi ne sont pas tous reliés.", "Vérifier les hypothèses d’activation, FPI, LPI, LPLV, capacité des centres et durée de suivi.");
  add(!(has("reporting", "registration") || has("registration", "registry")), "Reporting ↔ enregistrement", "Le registre prévu n’est pas documenté dans la préparation au reporting ou à l’enregistrement.", "Préparer les champs requis et confirmer la procédure auprès du registre compétent avant toute soumission.");
  add(!(has("regulatory", "jurisdiction") && has("regulatory", "submissionPlan") && has("reporting", "publicationPlan")), "Réglementaire ↔ reporting", "Juridiction, plan de soumission et plan de publication/reporting ne sont pas tous renseignés.", "Associer chaque exigence à une source versionnée et soumettre le dossier à la revue humaine compétente.");
  add(!(has("quality", "ctqFactors") && has("risks", "risks")), "Qualité ↔ risques", "Les facteurs critiques de qualité et le registre de risques ne sont pas suffisamment reliés.", "Définir les risques, propriétaires, seuils, actions de mitigation et règles d’escalade.");
  const categories = [{ key: "scientifique", label: "Cohérence scientifique", checked: has("question") && (has("objectives", "primaryObjective") || has("outcome", "primaryObjective")) && has("estimand"), message: "Question, objectifs, endpoints et estimand doivent former une chaîne explicite." }, { key: "statistique", label: "Préparation statistique", checked: has("statistics", "primaryAnalysis") && has("sample_size", "calculationType") && has("sap", "analysisSets"), message: "Analyse principale, populations d’analyse, SAP et hypothèses d’effectif sont à vérifier par un biostatisticien." }, { key: "operationnel", label: "Faisabilité opérationnelle", checked: has("schedule", "visits") && has("schedule", "assessments") && has("recruitment") && has("feasibility"), message: "Calendrier, visites, évaluations, recrutement, capacité et charge nécessitent une validation par les équipes de terrain." }, { key: "qualite", label: "Qualité et risques", checked: has("quality", "ctqFactors") && has("risks", "risks"), message: "Les facteurs critiques, risques, seuils et mesures de mitigation doivent être documentés." }, { key: "documentaire", label: "Protocole et documentation", checked: has("protocol", "synopsis") && has("regulatory", "submissionPlan") && has("reporting", "publicationPlan") && (has("registration", "registry") || has("reporting", "registration")), message: "Protocole, préparation réglementaire, enregistrement et reporting restent à soumettre à une revue humaine compétente." }]; const completed = categories.filter(category => category.checked).length; const allIssues = [...coherence.issues, ...auditIssues]; const critical = allIssues.filter(issue => issue.level === "INCOMPATIBLE"); return { status: critical.length ? "BLOQUÉ" : completed === categories.length && !auditIssues.length ? "PRÊT À REVOIR" : "À COMPLÉTER", score: Math.round((completed / categories.length) * 100), categories, coherenceIssues: allIssues, warning: "Audit de préparation uniquement : il n’équivaut pas à une approbation scientifique, statistique, éthique, réglementaire ou opérationnelle." }; }

const normalQuantile = (p: number) => { if (p >= 0.995) return 2.576; if (p >= 0.99) return 2.326; if (p >= 0.975) return 1.96; if (p >= 0.95) return 1.645; if (p >= 0.9) return 1.282; if (p >= 0.8) return 0.842; if (p >= 0.75) return 0.674; if (p >= 0.7) return 0.524; return 0.0; };
export function calculateSampleSize(input: { type: "BINARY" | "CONTINUOUS" | "CLUSTER"; alpha: number; power: number; p1?: number; p2?: number; meanDifference?: number; sd?: number; attrition?: number; allocationRatio?: number; clusterSize?: number; icc?: number }) {
  const alpha = input.alpha; const power = input.power; const zAlpha = normalQuantile(1 - alpha / 2); const zPower = normalQuantile(power); const ratio = input.allocationRatio ?? 1; let perGroup = 0; let assumptions: Record<string, unknown> = { ...input, zAlpha, zPower, allocationRatio: ratio };
  if (input.type === "BINARY") { if (input.p1 === undefined || input.p2 === undefined) throw new Error("p1 et p2 sont requis pour un endpoint binaire."); const pooled = (input.p1 + input.p2) / 2; perGroup = ((zAlpha * Math.sqrt(2 * pooled * (1 - pooled)) + zPower * Math.sqrt(input.p1 * (1 - input.p1) + input.p2 * (1 - input.p2))) ** 2) / ((input.p1 - input.p2) ** 2); }
  if (input.type === "CONTINUOUS") { if (input.meanDifference === undefined || input.sd === undefined || input.meanDifference === 0) throw new Error("Différence attendue et écart-type sont requis pour un endpoint continu."); perGroup = (2 * ((zAlpha + zPower) ** 2) * (input.sd ** 2)) / (input.meanDifference ** 2); }
  if (input.type === "CLUSTER") { if (!input.clusterSize || input.icc === undefined) throw new Error("Taille de cluster et ICC sont requis pour un essai en cluster."); const designEffect = 1 + (input.clusterSize - 1) * input.icc; perGroup = Math.max(2, input.clusterSize * 2); assumptions = { ...assumptions, designEffect, note: "Calcul simplifié de l’effet de design ; la puissance cluster requiert un modèle dédié." }; }
  const beforeAttrition = Math.ceil(perGroup); const afterAttrition = Math.ceil(beforeAttrition / (1 - Math.min(Math.max(input.attrition ?? 0, 0), 0.95))); return { perGroup: afterAttrition, total: Math.ceil(afterAttrition * (1 + ratio)), beforeAttrition, assumptions, warning: "Estimation pédagogique fondée sur les hypothèses saisies. Validation par biostatisticien requise avant toute décision de protocole ou de recrutement." };
}

export function forecastRecruitment(input: { centers: number; monthlyPatientsPerCenter: number; screeningRate: number; eligibilityRate: number; consentRate: number; attritionRate: number; target: number }) { const monthly = input.centers * input.monthlyPatientsPerCenter * input.screeningRate * input.eligibilityRate * input.consentRate; const adjustedTarget = Math.ceil(input.target / (1 - Math.min(Math.max(input.attritionRate, 0), 0.95))); const centralMonths = monthly ? Math.ceil(adjustedTarget / monthly) : null; return { monthlyExpected: Number(monthly.toFixed(2)), targetWithAttrition: adjustedTarget, estimatedMonths: centralMonths, pessimisticMonths: monthly ? Math.ceil(adjustedTarget / (monthly * 0.7)) : null, optimisticMonths: monthly ? Math.ceil(adjustedTarget / (monthly * 1.3)) : null, warning: "Projection fondée sur des hypothèses ; elle ne prédit pas le recrutement réel et doit être confrontée aux données de faisabilité de chaque centre." }; }

export function generateTheoreticalRandomisation(input: { ratioA: number; ratioB: number; blockSize: number; totalSlots: number; stratificationFactors?: string[]; seed: string }) { const ratioTotal = input.ratioA + input.ratioB; if (!ratioTotal || input.blockSize < ratioTotal || input.totalSlots < input.blockSize) throw new Error("Ratio, taille de bloc et nombre de créneaux incompatibles."); const perBlockA = Math.round(input.blockSize * input.ratioA / ratioTotal); const template = Array.from({ length: input.blockSize }, (_, index) => index < perBlockA ? "A" : "B"); const shuffle = (values: string[], block: number) => values.map((value, index) => ({ value, rank: hash(`${input.seed}-${block}-${index}`) })).sort((a, b) => a.rank - b.rank).map(item => item.value); const blocks = Array.from({ length: Math.ceil(input.totalSlots / input.blockSize) }, (_, block) => shuffle(template, block)); return { allocationRatio: `${input.ratioA}:${input.ratioB}`, blockSize: input.blockSize, stratificationFactors: input.stratificationFactors ?? [], allocationCodes: blocks.flat().slice(0, input.totalSlots), warning: "Liste théorique de démonstration sans identifiant de participant. La randomisation réelle doit être produite et administrée dans un système validé avec contrôle d’accès, audit trail et dissimulation d’allocation." }; }

export function assessOperationalLoad(input: { centers: number; coordinatorsPerCenter: number; visitsPerParticipant: number; targetParticipants: number; monthlyCapacityPerCoordinator: number; complexityLevel: "LOW" | "MEDIUM" | "HIGH" }) { const complexityMultiplier = input.complexityLevel === "HIGH" ? 1.5 : input.complexityLevel === "MEDIUM" ? 1.2 : 1; const totalVisits = input.visitsPerParticipant * input.targetParticipants; const monthlyCapacity = input.centers * input.coordinatorsPerCenter * input.monthlyCapacityPerCoordinator / complexityMultiplier; const months = monthlyCapacity > 0 ? Math.ceil(totalVisits / monthlyCapacity) : null; const workloadPerCenter = input.centers ? Math.ceil(totalVisits / input.centers) : 0; return { totalVisits, workloadPerCenter, effectiveMonthlyCapacity: Number(monthlyCapacity.toFixed(1)), estimatedOperationalMonths: months, complexityMultiplier, warning: "Modèle simplifié de charge : confirmer les temps de visite, tâches de pharmacie/laboratoire, monitoring, besoins de données et capacité réelle de chaque centre." }; }

export function assessCenterCapacity(input: { centers: number; activatedCenters: number; patientsScreenedPerCenterMonth: number; eligibilityRate: number; consentRate: number; startUpMonths: number }) { const activeCenters = Math.min(input.centers, input.activatedCenters); const enrolledPerMonth = activeCenters * input.patientsScreenedPerCenterMonth * input.eligibilityRate * input.consentRate; return { activeCenters, enrolledPerMonth: Number(enrolledPerMonth.toFixed(2)), startUpMonths: input.startUpMonths, sixMonthCapacity: Math.floor(enrolledPerMonth * Math.max(0, 6 - input.startUpMonths)), centerReadinessRatio: Number((activeCenters / input.centers).toFixed(2)), warning: "Capacité théorique par centre : confronter aux prévisions documentées, contrats, ressources de pharmacie/laboratoire et faisabilité locale." }; }

export function buildTrialTimeline(input: { designMonths: number; feasibilityMonths: number; regulatoryMonths: number; activationMonths: number; recruitmentMonths: number; treatmentMonths: number; followUpMonths: number; analysisMonths: number; reportingMonths: number }) { const phases = [{ key: "CONCEPTION", label: "Conception", durationMonths: input.designMonths }, { key: "FAISABILITE", label: "Faisabilité", durationMonths: input.feasibilityMonths }, { key: "REGLEMENTAIRE", label: "Préparation réglementaire", durationMonths: input.regulatoryMonths }, { key: "ACTIVATION", label: "Activation des centres", durationMonths: input.activationMonths }, { key: "RECRUTEMENT", label: "Recrutement", durationMonths: input.recruitmentMonths }, { key: "TRAITEMENT", label: "Traitement / intervention", durationMonths: input.treatmentMonths }, { key: "SUIVI", label: "Suivi et LPLV", durationMonths: input.followUpMonths }, { key: "ANALYSE", label: "Database lock et analyse", durationMonths: input.analysisMonths }, { key: "REPORTING", label: "Publication et reporting", durationMonths: input.reportingMonths }]; let startMonth = 0; const milestones = phases.map(phase => { const item = { ...phase, startMonth, endMonth: startMonth + phase.durationMonths }; startMonth = item.endMonth; return item; }); return { milestones, totalMonths: startMonth, warning: "Calendrier séquentiel indicatif. Les dépendances réelles, chevauchements, autorisations, recrutements et fenêtres de suivi doivent être validés avec l’équipe opérationnelle." }; }

export function scoreProtocolComplexity(input: { arms: number; primaryEndpoints: number; visitsPerParticipant: number; proceduresPerVisit: number; countries: number; blinded: boolean }) { const protocolComplexityScore = Math.min(100, Math.round(input.arms * 8 + input.primaryEndpoints * 12 + input.visitsPerParticipant * 4 + input.proceduresPerVisit * 3 + input.countries * 5 + (input.blinded ? 8 : 0))); const participantBurdenScore = Math.min(100, Math.round(input.visitsPerParticipant * 8 + input.proceduresPerVisit * 6)); const siteBurdenScore = Math.min(100, Math.round(input.arms * 9 + input.visitsPerParticipant * 5 + input.proceduresPerVisit * 5 + input.countries * 3 + (input.blinded ? 10 : 0))); const label = (score: number) => score >= 65 ? "ÉLEVÉ" : score >= 35 ? "MODÉRÉ" : "FAIBLE"; return { protocolComplexityScore, protocolComplexityLevel: label(protocolComplexityScore), participantBurdenScore, participantBurdenLevel: label(participantBurdenScore), siteBurdenScore, siteBurdenLevel: label(siteBurdenScore), warning: "Scores indicatifs non validés : ils soutiennent le dialogue de faisabilité et ne remplacent ni une étude de charge ni une validation opérationnelle." }; }

const hash = (value: string) => { let h = 2166136261; for (let index = 0; index < value.length; index += 1) h = Math.imul(h ^ value.charCodeAt(index), 16777619); return h >>> 0; };

export const designOptions = [{ id: "parallel", label: "Groupes parallèles", advantages: "Lecture directe et large applicabilité.", limits: "Nécessite souvent plus de participants.", complexity: "Modérée" }, { id: "crossover", label: "Cross-over", advantages: "Réduit la variabilité interindividuelle.", limits: "Risque de carry-over et besoin de washout.", complexity: "Élevée" }, { id: "cluster", label: "Randomisé en cluster", advantages: "Adapté aux interventions au niveau centre/groupe.", limits: "Inflation d’effectif et ICC requis.", complexity: "Élevée" }, { id: "stepped-wedge", label: "Stepped-wedge", advantages: "Transition progressive de tous les clusters.", limits: "Hypothèses temporelles et analyse complexe.", complexity: "Très élevée" }, { id: "single-arm", label: "Bras unique", advantages: "Simple et rapide dans certains contextes.", limits: "Absence de comparateur concurrent.", complexity: "Modérée" }];
