import { clinicalKnowledgeBase } from "./clinicalKnowledgeBase";
import { referenceRegistry } from "./referenceRegistry";
import type { KnowledgeItem, KnowledgeRelation, SourceReference, SyntheticTrial } from "./knowledgeModel";

const now = "2026-08-16";
const nextReview = "2027-02-16";
const sourceMap = new Map<string, SourceReference>(referenceRegistry.map(reference => [reference.id, { id: reference.id, title: reference.title, publisher: reference.publisher, url: reference.sourceUrl, version: reference.version, jurisdiction: reference.jurisdiction, publishedAt: reference.publicationDate, verifiedAt: reference.verifiedAt, status: reference.status === "VERIFIED_CURRENT" ? "VERIFIED" : "NEEDS_REVIEW" }]));
const source = (id: string): SourceReference => sourceMap.get(id) ?? { id: "cn-curated-knowledge", title: "Clinical Navigator curated knowledge seed", publisher: "Clinical Navigator", url: "https://github.com/Kevingiscard/Clinical-Navigator", verifiedAt: now, status: "NEEDS_REVIEW" };

const curated: KnowledgeItem[] = [
  { id: "CN-ENDPOINT-001", type: "CONCEPT", title: "Primary endpoint", shortDescription: "Outcome defined in advance as the main basis for the primary study conclusion.", fullDescription: "The primary endpoint must be clinically meaningful, measurable, prespecified and linked to the estimand and analysis plan.", language: ["fr", "en"], category: "Méthodologie", subcategory: "Outcomes", studyTypes: ["interventional", "observational"], phases: ["I", "II", "III", "IV"], audience: ["INVESTIGATOR", "BIOSTATISTICIAN", "SPONSOR"], keywords: ["endpoint", "primary outcome", "critère principal"], synonyms: ["outcome", "variable principale", "critère de jugement"], relatedConcepts: ["CN-ESTIMAND-001", "CN-STAT-COX-001"], sources: [source("ich-e8-r1"), source("ich-e9-r1")], pitfalls: [{ id: "CN-ENDPOINT-PITFALL-001", title: "Changing the primary endpoint after unblinding", description: "A post hoc change may bias interpretation and requires documented governance." }], status: "NEEDS_REVIEW", createdAt: now, updatedAt: now, nextReviewAt: nextReview, version: "1.0.0", confidence: 0.86, aiAllowed: true, offlineAvailable: true },
  { id: "CN-ESTIMAND-001", type: "CONCEPT", title: "Estimand", shortDescription: "Precise description of the treatment effect a study aims to estimate.", fullDescription: "An estimand specifies population, treatment conditions, variable, summary measure and handling of intercurrent events.", language: ["fr", "en"], category: "Statistiques", subcategory: "Estimands", audience: ["BIOSTATISTICIAN", "INVESTIGATOR", "SPONSOR"], keywords: ["estimand", "intercurrent event", "treatment effect"], synonyms: ["question d'effet", "effet du traitement", "événement intercurrent"], relatedConcepts: ["CN-ENDPOINT-001", "CN-STAT-COX-001"], sources: [source("ich-e9-r1")], status: "NEEDS_REVIEW", createdAt: now, updatedAt: now, nextReviewAt: nextReview, version: "1.0.0", confidence: 0.88, aiAllowed: true, offlineAvailable: true },
  { id: "CN-STAT-COX-001", type: "STATISTICAL_METHOD", title: "Cox proportional hazards model", shortDescription: "A survival model that estimates relative hazard under proportional-hazards assumptions.", language: ["fr", "en"], category: "Statistiques", subcategory: "Survival", keywords: ["Cox", "hazard ratio", "survival"], synonyms: ["modèle de risques proportionnels", "survie"], prerequisites: ["CN-ESTIMAND-001"], sources: [source("ich-e9-r1")], pitfalls: [{ id: "CN-STAT-COX-PITFALL-001", title: "Unexamined proportional hazards", description: "The proportional-hazards assumption must be assessed and sensitivity analyses considered." }], status: "NEEDS_REVIEW", createdAt: now, updatedAt: now, nextReviewAt: nextReview, version: "1.0.0", confidence: 0.82, aiAllowed: true, offlineAvailable: true },
  { id: "CN-REG-EU-001", type: "REGULATION", title: "EU Clinical Trials Regulation", shortDescription: "European Union framework for clinical trials on medicinal products.", language: ["fr", "en"], category: "Réglementaire", jurisdiction: ["European Union"], keywords: ["CTR", "536/2014", "CTIS"], synonyms: ["règlement essais cliniques", "Clinical Trials Regulation"], sources: [source("eu-ctr-536-2014"), source("ema-ctis")], status: "NEEDS_REVIEW", createdAt: now, updatedAt: now, nextReviewAt: nextReview, version: "536/2014", confidence: 0.8, aiAllowed: true, offlineAvailable: true },
  { id: "CN-REG-BJ-001", type: "JURISDICTION_RULE", title: "Bénin — couverture réglementaire à confirmer", shortDescription: "No national route is marked verified in this release; local confirmation is mandatory.", language: ["fr", "en"], category: "Juridictions", jurisdiction: ["Bénin"], keywords: ["Bénin", "Benin", "autorité", "éthique"], synonyms: ["essai clinique au Bénin", "recherche au Bénin"], sources: [source("cn-curated-knowledge")], status: "NEEDS_REVIEW", createdAt: now, updatedAt: now, nextReviewAt: nextReview, version: "1.0.0", confidence: 0.15, aiAllowed: true, offlineAvailable: true },
  { id: "CN-ETHICS-CONSENT-001", type: "ETHICS_RULE", title: "Informed consent", shortDescription: "Process that supports voluntary, informed and documented participation.", language: ["fr", "en"], category: "Éthique", subcategory: "Consent", keywords: ["consentement", "informed consent", "voluntary"], synonyms: ["information participant", "reconsent", "assent"], sources: [source("ich-e6-r3"), source("cnil-mr-001")], status: "NEEDS_REVIEW", createdAt: now, updatedAt: now, nextReviewAt: nextReview, version: "1.0.0", confidence: 0.84, aiAllowed: true, offlineAvailable: true },
  { id: "CN-CHECKLIST-PROTOCOL-001", type: "CHECKLIST", title: "Protocol quality checklist", shortDescription: "Educational checklist for research question, population, outcomes, estimand, analysis and governance.", language: ["fr", "en"], category: "Formation", keywords: ["protocol", "checklist", "protocole"], synonyms: ["quality checklist", "revue protocole"], checklist: ["research-question", "population", "endpoint", "estimand", "sample-size", "safety", "ethics"].map(id => ({ id: `CN-CHECK-${id}`, label: id, required: true })), sources: [source("ich-e8-r1"), source("ich-e6-r3")], status: "NEEDS_REVIEW", createdAt: now, updatedAt: now, nextReviewAt: nextReview, version: "1.0.0", aiAllowed: true, offlineAvailable: true },
];

const mappedClinical: KnowledgeItem[] = clinicalKnowledgeBase.map(entry => ({ id: `CN-KB-${entry.id.toUpperCase()}`, type: entry.category === "Statistiques" ? "STATISTICAL_METHOD" : entry.category === "Réglementaire" ? "REGULATION" : entry.category === "Éthique" ? "ETHICS_RULE" : entry.category === "Glossaire" ? "GLOSSARY_TERM" : "CONCEPT", title: entry.question.fr, shortDescription: entry.answer.fr.slice(0, 240), fullDescription: entry.answer.fr, language: ["fr", "en"], category: entry.category, jurisdiction: entry.geographicScope, keywords: [...entry.keywords.fr, ...entry.keywords.en], synonyms: [], sources: [source("cn-curated-knowledge")], status: "NEEDS_REVIEW", createdAt: now, updatedAt: now, verifiedAt: undefined, nextReviewAt: nextReview, version: "2.0.0", confidence: entry.evidenceLevel === "A" ? 0.9 : entry.evidenceLevel === "B" ? 0.75 : 0.55, aiAllowed: true, offlineAvailable: true }));

export const knowledgeItems: KnowledgeItem[] = [...curated, ...mappedClinical];
export const clinicalKnowledgeGraph: KnowledgeRelation[] = [
  { id: "REL-ENDPOINT-ESTIMAND", from: "CN-ENDPOINT-001", type: "RELATED_TO", to: "CN-ESTIMAND-001", status: "NEEDS_REVIEW", sourceIds: ["ich-e9-r1"] },
  { id: "REL-ESTIMAND-COX", from: "CN-ESTIMAND-001", type: "CALCULATED_BY", to: "CN-STAT-COX-001", status: "NEEDS_REVIEW", sourceIds: ["ich-e9-r1"] },
  { id: "REL-REG-EU-CTIS", from: "CN-REG-EU-001", type: "SUPPORTED_BY", to: "CN-REG-EU-001", status: "NEEDS_REVIEW", sourceIds: ["eu-ctr-536-2014", "ema-ctis"] },
  { id: "REL-CHECK-PROTOCOL", from: "CN-CHECKLIST-PROTOCOL-001", type: "USED_IN", to: "CN-ENDPOINT-001", status: "NEEDS_REVIEW", sourceIds: ["ich-e8-r1"] },
];
export const TrialDesignKnowledgeBase = knowledgeItems.filter(item => ["Méthodologie", "Statistiques", "Opérations"].includes(item.category) || item.id.startsWith("CN-ENDPOINT") || item.id.startsWith("CN-ESTIMAND"));
export const TrialAuditKnowledgeBase = knowledgeItems.filter(item => ["Qualité", "Opérations", "Données", "Réglementaire"].includes(item.category));
export const StatisticalKnowledgeBase = knowledgeItems.filter(item => item.type === "STATISTICAL_METHOD" || item.category === "Statistiques");
export const RegulatoryKnowledgeBase = knowledgeItems.filter(item => ["REGULATION", "LAW", "JURISDICTION_RULE"].includes(item.type));
export const EthicsKnowledgeBase = knowledgeItems.filter(item => item.type === "ETHICS_RULE");
export const ConsentKnowledgeBase = knowledgeItems.filter(item => item.id.includes("CONSENT") || item.keywords.some(keyword => keyword.toLowerCase().includes("consent")));
export const QualityKnowledgeBase = knowledgeItems.filter(item => item.category === "Qualité");
export const DataManagementKnowledgeBase = knowledgeItems.filter(item => item.category === "Données");
export const SafetyKnowledgeBase = knowledgeItems.filter(item => item.category === "Sécurité");
export const ToolsKnowledgeBase = knowledgeItems.filter(item => item.type === "CALCULATION");
export const SyntheticTrialDataset: SyntheticTrial[] = [{ id: "SYN-TRIAL-001", label: "SYNTHETIC / EDUCATIONAL", condition: "Synthetic condition", intervention: "Synthetic intervention", sites: 4, participants: 120, visits: 5, adverseEvents: 17 }];
export const knowledgeDatasetVersion = "1.0.0";
export const knowledgeStats = { total: knowledgeItems.length, relations: clinicalKnowledgeGraph.length, verified: knowledgeItems.filter(item => item.status === "VERIFIED").length, needsReview: knowledgeItems.filter(item => item.status === "NEEDS_REVIEW").length, offlineAvailable: knowledgeItems.filter(item => item.offlineAvailable).length, sources: new Set(knowledgeItems.flatMap(item => item.sources.map(source => source.id))).size, jurisdictions: new Set(knowledgeItems.flatMap(item => item.jurisdiction ?? [])).size };
