import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from "@/components/ui/accordion";
import { Alert, AlertDescription, AlertTitle } from "@/components/ui/alert";
import { Button } from "@/components/ui/button";
import { Checkbox } from "@/components/ui/checkbox";
import { Progress } from "@/components/ui/progress";
import { trpc } from "@/lib/trpc";
import type { GuidanceResponse } from "@shared/clinicalContent";
import { AlertTriangle, ArrowLeft, CheckCircle2, ClipboardCheck, Clock3, ExternalLink, FileText, ShieldAlert, UsersRound } from "lucide-react";
import { useMemo, useState } from "react";
import { Link } from "wouter";
import { ContentStatusBadge, PriorityBadge } from "./StatusBadge";

const modeLabels = { rapide: "Rapide — priorités et prochaines actions", detaille: "Détaillé — parcours opérationnel complet", expert: "Expert — détails, sources et limites" };

export function GuidanceReport({ report, onRestart }: { report: GuidanceResponse; onRestart: () => void }) {
  const [checked, setChecked] = useState<string[]>([]); const [feedback, setFeedback] = useState<"yes" | "no" | null>(null); const feedbackMutation = trpc.clinical.feedback.useMutation();
  const progress = useMemo(() => Math.round((checked.length / report.scenario.checklist.length) * 100), [checked.length, report.scenario.checklist.length]);
  const isQuick = report.mode === "rapide"; const isExpert = report.mode === "expert";
  const toggle = (item: string) => setChecked(current => current.includes(item) ? current.filter(value => value !== item) : [...current, item]);
  return <section className="mx-auto max-w-5xl px-4 py-10 sm:px-6 lg:px-8">
    <div className="mb-7 flex flex-wrap items-center justify-between gap-3"><Button variant="outline" onClick={onRestart} className="border-[#c9ddd6] bg-white text-[#23464a]"><ArrowLeft className="mr-2 h-4 w-4" />Nouveau cas</Button><div className="flex items-center gap-2"><ContentStatusBadge status={report.scenario.status} /><span className="text-xs text-[#617875]">Workflow v{report.scenario.version}</span></div></div>
    {report.blocked && <Alert className="mb-6 border-rose-300 bg-rose-50 text-rose-950"><AlertTriangle className="h-5 w-5" /><AlertTitle>Donnée sensible potentielle détectée</AlertTitle><AlertDescription>{report.sensitiveDataWarning}</AlertDescription></Alert>}
    <article className={`overflow-hidden rounded-3xl border shadow-sm ${report.priority === "CRITIQUE" ? "border-rose-300 bg-rose-50" : "border-[#d8e7e1] bg-white"}`}><div className="grid gap-6 p-6 md:grid-cols-[1fr_auto] md:p-9"><div><div className="mb-3 flex flex-wrap items-center gap-3"><span className="text-xs font-bold uppercase tracking-[0.15em] text-[#568178]">Analyse structurée</span><PriorityBadge priority={report.priority} /></div><h1 className="font-serif text-3xl font-bold tracking-tight text-[#0d2b36] md:text-4xl">{report.scenario.title}</h1><p className="mt-3 max-w-3xl text-base leading-7 text-[#48635f]">{report.summary}</p></div><div className="rounded-2xl bg-[#eaf4ef] p-4 text-sm text-[#29564f] md:max-w-64"><p className="font-bold">Pourquoi cette priorité ?</p><p className="mt-2 leading-5">{report.priorityReason}</p></div></div><div className="border-t border-[#e5efeb] bg-[#f7fbf9] p-6 md:px-9"><div className="flex gap-3"><ShieldAlert className="mt-0.5 h-5 w-5 shrink-0 text-[#227868]" /><div><p className="font-bold text-[#16393e]">Ce qu’il faut faire maintenant</p><p className="mt-1 leading-6 text-[#3d5c58]">{report.immediateAction}</p></div></div></div></article>
    <p className="mt-5 rounded-xl border border-[#d8e7e1] bg-white px-4 py-3 text-sm font-semibold text-[#35625d]">Mode sélectionné : <span className="text-[#176d60]">{modeLabels[report.mode]}</span></p>
    <div className="mt-6 grid gap-6 lg:grid-cols-[1.55fr_0.85fr]"><div className="rounded-2xl border border-[#d8e7e1] bg-white p-2 shadow-sm"><Accordion type="multiple" defaultValue={isQuick ? ["actions", "deadlines", "limits"] : ["actions", "actors", "documents", "deadlines", "checklist", "sources", "limits"]}>
      <Section value="actions" title="Actions à mener" icon={<CheckCircle2 />}><ol className="space-y-3">{report.scenario.actions.map((action, index) => <li key={action} className="flex gap-3"><span className="flex h-6 w-6 shrink-0 items-center justify-center rounded-full bg-[#dff1e9] text-xs font-bold text-[#146557]">{index + 1}</span><span>{action}</span></li>)}</ol></Section>
      <Section value="deadlines" title="Délais et niveau de confiance" icon={<Clock3 />}><div className="grid gap-3">{report.deadlines.map(item => <div key={item.label} className="rounded-xl border border-[#deece6] bg-[#f6fbf8] p-3"><p className="font-bold text-[#244b49]">{item.label}</p><p className="mt-1 text-sm text-[#476762]">{item.timing}</p><p className="mt-2 text-xs text-[#66817b]">Source à vérifier : {item.source} · Niveau : {item.confidence}</p></div>)}</div></Section>
      {!isQuick && <><Section value="actors" title="Acteurs concernés : informer ≠ décider ≠ documenter" icon={<UsersRound />}><div className="overflow-x-auto"><table className="w-full min-w-[480px] text-left text-sm"><thead><tr className="border-b border-[#e2eeea] text-xs uppercase tracking-wide text-[#66817c]"><th className="pb-2 pr-3">Acteur</th><th className="pb-2 pr-3">Rôle</th><th className="pb-2">Quand</th></tr></thead><tbody>{report.scenario.actors.map(actor => <tr key={actor.role} className="border-b border-[#edf3f1] align-top"><td className="py-3 pr-3 font-semibold text-[#183b40]">{actor.role}</td><td className="py-3 pr-3 text-[#526b67]">{actor.responsibility}</td><td className="py-3 text-[#526b67]">{actor.when}</td></tr>)}</tbody></table></div></Section><Section value="documents" title="Documents et vérifications" icon={<FileText />}><div className="grid gap-2">{[...report.scenario.documents, ...report.scenario.checks].map(item => <div key={item} className="rounded-xl bg-[#f3f8f6] px-3 py-2.5 text-sm text-[#365652]">{item}</div>)}</div></Section><Section value="checklist" title="Checklist interactive" icon={<ClipboardCheck />}><div className="mb-4 flex items-center gap-3"><Progress value={progress} className="h-2 bg-[#e1ece7]" /><span className="w-12 text-right text-xs font-bold text-[#52746e]">{progress}%</span></div><div className="grid gap-2">{report.scenario.checklist.map(item => <label key={item} className="flex cursor-pointer items-start gap-3 rounded-xl px-2 py-2 hover:bg-[#f2f8f5]"><Checkbox checked={checked.includes(item)} onCheckedChange={() => toggle(item)} className="mt-0.5 border-[#83a69f]" /><span className={checked.includes(item) ? "text-[#71908a] line-through" : "text-[#365652]"}>{item}</span></label>)}</div></Section></>}
      {isExpert && <><Section value="escalation" title="Escalade, erreurs et exemple" icon={<ShieldAlert />}><ul className="space-y-2">{report.scenario.escalation.map(item => <li key={item} className="flex gap-2"><span className="mt-2 h-1.5 w-1.5 rounded-full bg-[#d46c4f]" />{item}</li>)}</ul><p className="mt-4 font-semibold text-[#7b4536]">Erreurs à éviter</p><ul className="mt-2 space-y-2">{report.scenario.mistakes.map(item => <li key={item} className="flex gap-2"><span className="mt-2 h-1.5 w-1.5 rounded-full bg-[#d46c4f]" />{item}</li>)}</ul><p className="mt-4 rounded-xl bg-[#f5f8f6] p-3">Exemple simulé : {report.scenario.example}</p></Section><Section value="sources" title="Références et sources" icon={<FileText />}><div className="grid gap-3">{report.sourceRecords.map(source => <a href={source.url} target="_blank" rel="noreferrer" key={source.id} className="rounded-xl border border-[#dfece7] p-3 hover:border-[#91c4b7]"><div className="flex items-start justify-between gap-3"><div><p className="font-semibold text-[#1d4447]">{source.title}</p><p className="mt-1 text-xs text-[#66817c]">{source.publisher} · {source.jurisdiction} · {source.publishedAt}</p></div><ExternalLink className="h-4 w-4 shrink-0 text-[#287c71]" /></div><p className="mt-2 text-sm leading-5 text-[#54706b]">{source.scope}</p></a>)}</div></Section></>}
      <Section value="limits" title="Limites et informations manquantes" icon={<AlertTriangle />}><ul className="space-y-2">{report.missingInformation.map(item => <li key={item} className="flex gap-2"><span className="mt-2 h-1.5 w-1.5 rounded-full bg-amber-500" />{item}</li>)}</ul><div className="mt-4 rounded-xl bg-[#f8f3ea] p-4 text-sm leading-6 text-[#69572f]">{report.limits.map(limit => <p key={limit} className="mb-2 last:mb-0">{limit}</p>)}</div></Section>
    </Accordion></div><aside className="space-y-5"><div className="rounded-2xl bg-[#0d2b36] p-6 text-white shadow-sm"><p className="text-xs font-bold uppercase tracking-[0.16em] text-[#a7d6c4]">Rappel de prudence</p><p className="mt-3 font-serif text-xl font-bold leading-7">La source, le protocole et les personnes habilitées priment sur l’outil.</p><Link href="/fr/limites" className="mt-4 inline-flex text-sm font-semibold text-[#b7e0cf] hover:text-white">Comprendre les limites</Link></div><div className="rounded-2xl border border-[#d8e7e1] bg-white p-5"><p className="font-bold text-[#16393e]">Cette réponse vous a-t-elle aidé ?</p><div className="mt-3 flex gap-2"><Button size="sm" variant={feedback === "yes" ? "default" : "outline"} className={feedback === "yes" ? "bg-[#227868]" : "border-[#c9ddd6]"} onClick={() => { setFeedback("yes"); feedbackMutation.mutate({ helpful: true, scenarioId: report.scenario.id }); }}>Oui</Button><Button size="sm" variant={feedback === "no" ? "default" : "outline"} className={feedback === "no" ? "bg-[#b85d43]" : "border-[#c9ddd6]"} onClick={() => { setFeedback("no"); feedbackMutation.mutate({ helpful: false, scenarioId: report.scenario.id }); }}>Non</Button></div></div></aside></div>
  </section>;
}
function Section({ value, title, icon, children }: { value: string; title: string; icon: React.ReactNode; children: React.ReactNode }) { return <AccordionItem value={value} className="border-b border-[#e5efeb] px-4 last:border-0"><AccordionTrigger className="gap-3 py-4 text-left text-sm font-bold text-[#1c4246] hover:no-underline"><span className="flex h-8 w-8 shrink-0 items-center justify-center rounded-lg bg-[#e7f4ee] text-[#207766]">{icon}</span>{title}</AccordionTrigger><AccordionContent className="pb-5 pl-11 text-sm leading-6 text-[#4b6561]">{children}</AccordionContent></AccordionItem>; }
