import { jurisdictionRegistry } from "@shared/jurisdictionRegistry";
import { ExternalLink, Globe2, ShieldAlert } from "lucide-react";
export function JurisdictionCoverageCard() {
  const sourceFound = jurisdictionRegistry.filter(item => item.status === "SOURCE_FOUND_NEEDS_LOCAL_REVIEW").length;
  const localReview = jurisdictionRegistry.filter(item => item.status === "PORTAL_NOT_CONFIRMED").length;
  return <section className="rounded-2xl border border-[#dbe8e3] bg-white p-6 shadow-sm" aria-labelledby="jurisdiction-coverage-title">
    <div className="flex flex-wrap items-start justify-between gap-4"><div className="flex items-start gap-3"><span className="flex h-10 w-10 items-center justify-center rounded-xl bg-[#e8f4ee] text-[#237162]"><Globe2 className="h-5 w-5" /></span><div><p className="text-xs font-bold uppercase tracking-[0.15em] text-[#39806f]">Couverture internationale</p><h2 id="jurisdiction-coverage-title" className="mt-2 font-serif text-2xl font-bold text-[#143c41]">Portail trouvé ne signifie pas autorisation.</h2></div></div><span className="rounded-full bg-[#fff5df] px-3 py-1 text-xs font-bold text-[#8d6422]">Revue locale obligatoire</span></div>
    <p className="mt-4 text-sm leading-6 text-[#607771]">Le registre fournit un point de départ officiel et une date de contrôle. Il ne remplace pas une qualification du dossier, une consultation du comité d’éthique ou une confirmation de l’autorité compétente.</p>
    <div className="mt-5 grid gap-3 sm:grid-cols-2"><div className="rounded-xl bg-[#edf8f2] p-4"><p className="text-2xl font-bold text-[#237162]">{sourceFound}</p><p className="mt-1 text-xs font-semibold text-[#4d7068]">portails officiels repérés</p></div><div className="rounded-xl bg-[#fff6e4] p-4"><p className="text-2xl font-bold text-[#9a6a1e]">{localReview}</p><p className="mt-1 text-xs font-semibold text-[#766044]">juridictions sans portail national confirmé</p></div></div>
    <div className="mt-5 grid gap-2">{jurisdictionRegistry.slice(0, 8).map(item => <div key={item.slug} className="flex items-center justify-between gap-3 rounded-lg border border-[#e4eee9] px-3 py-2 text-sm"><span className="font-semibold text-[#294d4b]">{item.country}</span>{item.officialPortal ? <a className="inline-flex items-center gap-1 text-xs font-bold text-[#237162]" href={item.officialPortal} target="_blank" rel="noreferrer">{item.authorityLabel}<ExternalLink className="h-3 w-3" /></a> : <span className="inline-flex items-center gap-1 text-xs font-bold text-[#9a6a1e]"><ShieldAlert className="h-3 w-3" />À confirmer</span>}</div>)}</div>
  </section>;
}
